/**
 * Cihaz arıza rehberi — hizmet sayfalarında (React) ve önceden render edilen SEO HTML'inde
 * (scripts/prerender.ts) aynı kaynaktan kullanılır.
 *
 * Kaynak: Google otomatik tamamlama ve "Diğer sorular" verilerinde öne çıkan gerçek arıza aramaları
 * (Eylül 2026) ile Eşli Teknik'in Google yorumlarında geçen işler. Metinler özgündür; fiyat,
 * süre garantisi veya yetkili servis iddiası içermez.
 */

export type DeviceFault = { title: string; causes: string; check: string };
export type DeviceFaultGuide = {
  description: string;
  faults: DeviceFault[];
  /** İnceleme, süre ve ücret — arıza bölümünde geçmeyen servis bilgisi. */
  service: string;
  /** Beklemeden servis istenmesi gereken durumlar — arızalarda anlatılanları tekrar etmez. */
  urgent: string;
};

export const deviceFaultGuides: Record<string, DeviceFaultGuide> = {
  "Çamaşır Makinesi": {
    description: "Konya’da çamaşır makinesi su almıyor, boşaltmıyor, sıkmıyor ya da sesli çalışıyorsa Eşli Teknik’e WhatsApp’tan yazın. Online servis takibi.",
    faults: [
      { title: "Çamaşır makinesi su almıyor", causes: "Musluk veya şebeke basıncı, su giriş hortumundaki süzgecin kireç ve tortuyla tıkanması, su giriş ventili, kapak kilidinin kapalı olduğunu algılamaması ya da kontrol kartı bu belirtiye yol açabilir. Makine su almadan uğulduyor veya bekliyorsa ventil ve kilit tarafı öne çıkar.", check: "Musluğun sonuna kadar açık olduğunu, evin diğer musluklarında su bulunduğunu ve giriş hortumunun kıvrılmadığını kontrol edin. Kapağı sıkıca kapatıp programı yeniden başlatın. Hortum süzgecini yalnızca musluk kapalıyken ve kullanım kılavuzundaki adımlarla temizleyin." },
      { title: "Çamaşır makinesi suyu boşaltmıyor, içinde su kalıyor", causes: "En sık neden, pompa filtresine kaçan bozuk para, düğme, çorap veya tüy birikimidir. Tahliye hortumunun kıvrılması, lavabo sifonunun tıkanması ya da tahliye pompasının arızalanması da suyun içeride kalmasına neden olur. Pompa çalışırken ses gelip su çıkmıyorsa tıkanıklık, hiç ses gelmiyorsa pompa veya bağlantısı incelenir.", check: "Sıcak yıkamadan hemen sonra filtreyi açmayın; suyun soğumasını bekleyin. Önüne havlu ve düz bir kap koyarak ön alt kapaktaki filtreyi kılavuza göre açıp temizleyin. Tahliye hortumunun kıvrık olmadığını ve sifon bağlantısının açık olduğunu kontrol edin." },
      { title: "Çamaşır makinesi sıkma yapmıyor, sıkmaya geçmiyor", causes: "Makine içindeki suyu boşaltamıyorsa sıkmaya geçmez; bu yüzden önce tahliye kontrol edilir. Tek bir ağır parça (battaniye, paspas) yükü dengesizleştirip sıkmayı durdurabilir. Tahliye ve yük dengesi sorunsuzsa motor kömürleri, takometre, motor veya kontrol kartı değerlendirilir.", check: "Çamaşırları tamburun içinde dağıtın ya da birkaç parça daha ekleyerek yükü dengeleyin. Sıkma devri kapalı veya çok düşük bir program seçilmediğinden emin olun. Kısa bir sıkma programını az yükle deneyin." },
      { title: "Sıkmada aşırı sallanma, yürüme ve ses", causes: "Dengesiz yük ve düzgün olmayan zemin en yaygın nedenlerdir. Yeni kurulan makinede nakliye cıvatalarının sökülmemesi şiddetli sarsıntı yapar. Sorun devam ediyorsa amortisörler, askı yayları veya kazan rulmanı incelenir; sıkmada artan uğultu ve metalik ses genellikle rulman ve keçe grubuna işaret eder.", check: "Makinenin ayaklarını ayarlayıp dört köşenin zemine eşit bastığını kontrol edin. Yeni kurulumda arka taraftaki nakliye cıvatalarının çıkarıldığından emin olun. Tamburu elle çevirip içeride sıkışmış metal bir cisim olup olmadığına bakın." },
      { title: "Çamaşır makinesi altından su akıtıyor", causes: "Giriş veya tahliye hortumu bağlantıları, deterjan çekmecesinde taşma, kapak körüğündeki yırtık ya da sıkışmış küçük parçalar ve pompa contası su kaçağının başlıca kaynaklarıdır. Suyun yıkamanın hangi aşamasında aktığı, kaynağın bulunmasına yardım eder.", check: "Su yayılıyorsa önce musluğu kapatın ve fişi kuru elle çekin. Hortum bağlantılarını, deterjan çekmecesini ve kapak körüğünü gözle kontrol edin. Elde yıkama deterjanı kullanmak aşırı köpük ve taşma yapabilir." },
      { title: "Çamaşır makinesi sigorta attırıyor", causes: "Isıtıcı rezistansta kaçak, motor veya kablo hasarı ve nem alan elektrik bağlantıları sigortanın atmasına neden olur. Sigorta genellikle ısıtma veya sıkma aşamasında atıyorsa arızanın yeri buna göre daraltılır.", check: "Makineyi tekrar tekrar çalıştırmayın ve farklı prizlerde denemeyin. Fişi çekili tutun; hangi aşamada sigorta attığını not edip servis talebinizde paylaşın." },
    ],
    service: "İnceleme sonrasında arızanın kaynağı, yapılacak işlem ve varsa parça ihtiyacı size açıklanır; onayınız alınmadan parça değiştirilmez. Filtre tıkanıklığı, hortum ve ayar kaynaklı sorunlar çoğu zaman aynı ziyarette çözülür. Pompa, kapak kilidi, amortisör, rezistans, kazan rulmanı veya kontrol kartı gerektiren işlerde süre, modele ve parça temin durumuna göre değişir. Ücret; tespit, işçilik ve parça netleştikten sonra paylaşılır.",
    urgent: "Kablo veya prizde ısınma, yanık kokusu ya da gövdeye dokunurken elektrik çarpması hissi varsa makineyi çalıştırmayın ve fişini çekin. Aynı arıza kısa aralıklarla tekrarlıyorsa makineyi kapatıp açmak gibi geçici çözümler yerine kök nedenin incelenmesi gerekir.",
  },
  "Buzdolabı": {
    description: "Konya’da buzdolabı soğutmuyor, buzlanıyor, su akıtıyor ya da sesli çalışıyorsa Eşli Teknik’e WhatsApp’tan yazın. Online servis takibi.",
    faults: [
      { title: "Buzdolabı çalışıyor ama soğutmuyor", causes: "Işık yanıyor ve motor sesi geliyor ama iç ısınıyorsa fan motoru, hava kanalındaki buz tıkanıklığı, sıcaklık sensörü, defrost sistemi ya da kompresör ve rölesi incelenir.", check: "Sıcaklık ayarının yanlışlıkla değişmediğini, kapının tam kapandığını ve dolabın arkasında hava dolaşımı için boşluk kaldığını kontrol edin. Arka ızgarayı fişi çektikten sonra tozdan arındırın. İçeriye sıcak yemek konulduysa soğutmanın toparlanması birkaç saat sürebilir." },
      { title: "Buzdolabının altı soğutmuyor, dondurucu soğutuyor", causes: "No-frost buzdolaplarında soğuk hava dondurucudan bir kanal ve fan aracılığıyla alt bölmeye taşınır. Bu kanal buzla tıkanırsa, fan çalışmazsa ya da hava akışını ayarlayan kapakçık arızalanırsa dondurucu soğuk kalırken alt bölme ısınır. Sorunun kökü genellikle defrost sistemidir.", check: "Alt bölmenin arka duvarındaki hava çıkışlarını ürünlerin kapatmadığından emin olun. Dondurucunun arka duvarında kalın bir buz tabakası varsa bunu servis talebinizde belirtin. Buzu bıçak veya sivri bir aletle kazımayın." },
      { title: "Buzdolabı buzlanma ve karlanma yapıyor", causes: "Kapı contasının tam oturmaması, kapının sık ve uzun açılması içeriye nemli hava alır ve buzlanma yapar. No-frost modellerde sürekli buzlanma defrost rezistansı, termik koruma veya zamanlayıcı arızasına işaret eder.", check: "Contanın arasına bir kağıt sıkıştırıp kapıyı kapatın; kağıt kolayca kayıyorsa conta tam kapatmıyor olabilir." },
      { title: "Buzdolabı su akıtıyor, içinde su birikiyor", causes: "Alt bölmenin arka duvarındaki gider deliği tıkanırsa eriyen su dışarı atılamaz ve rafların altında birikir. Buzdolabının öne doğru eğimli durması veya dondurucudan gelen su kanalının buzlanması da su akıtmaya neden olur.", check: "Arka duvardaki gider deliğini kullanım kılavuzunda anlatılan şekilde ılık suyla açın. Dolabın hafifçe arkaya eğimli ve sabit durduğunu kontrol edin." },
      { title: "Buzdolabı sesli çalışıyor ya da hiç durmadan çalışıyor", causes: "Fan pervanesine buz sürtünmesi, kompresör takozlarının gevşemesi veya dolabın düz olmayan zeminde durması belirgin ses yapar. Sürekli çalışma ise conta sızıntısı, kirli kondenser, çok sıcak ortam ya da sıcaklık sensörüyle ilgili olabilir. Kısa tıklamalar ve akış sesleri normal çalışma sesleridir.", check: "Dolabın duvara ve dolaplara değmediğini, ayaklarının sağlam bastığını kontrol edin. Sesin kapı açıkken değişip değişmediğini not edin; bu, fan kaynaklı sesi ayırt etmeye yardım eder." },
    ],
    service: "Conta, gider deliği, sensör ve fan kaynaklı işlemler çoğunlukla aynı ziyarette tamamlanır. Defrost sistemi, kompresör veya soğutma devresindeki bir kaçağın onarımı gibi işlerde süre, kaçak tespitine ve parça temin durumuna göre uzayabilir. İnceleme sonrası yapılacak işlem ve ücret açıklanır; onayınız olmadan parça değiştirilmez.",
    urgent: "Yanık kokusu, prizde ısınma veya sigorta attırma varsa buzdolabını prizden çekin. Soğutma belirgin biçimde azaldıysa çabuk bozulan gıdaları başka bir soğutucuya ya da serin bir ortama alın; kapıyı gereksiz açmamak iç sıcaklığın daha yavaş yükselmesini sağlar.",
  },
  "Bulaşık Makinesi": {
    description: "Konya’da bulaşık makinesi su almıyor, boşaltmıyor, temiz yıkamıyor ya da su akıtıyorsa Eşli Teknik’e WhatsApp’tan yazın. Online servis takibi.",
    faults: [
      { title: "Bulaşık makinesi su almıyor, yıkamaya geçmiyor", causes: "Kapalı musluk, giriş hortumundaki süzgecin tıkanması, su giriş ventili veya su taşma korumasının devreye girmesi makinenin su almamasına yol açar. Makine su alıyor ama yıkamaya geçmiyorsa yıkama motoru, ısıtıcı veya kontrol kartı değerlendirilir.", check: "Musluğun açık ve hortumun kıvrılmamış olduğunu kontrol edin. Kapağın tık sesiyle tam kapandığından emin olun. Taban bölgesinden su sızıntısı varsa makine kendini korumaya alabilir; bu durumu servis talebinizde belirtin." },
      { title: "Bulaşık makinesi suyu boşaltmıyor, dipte su kalıyor", causes: "Makine tabanındaki filtrenin yemek artığıyla tıkanması en sık nedendir. Tahliye hortumunun kıvrılması, lavabo sifonuna bağlantı noktasının tıkanması ya da tahliye pompasının arızalanması da suyun dipte kalmasına neden olur.", check: "Alt sepeti çıkarıp tabandaki filtreyi kılavuza göre söküp temizleyin. Lavabo altında tahliye hortumunun ezilmediğini ve sifona bağlandığı noktanın tıkalı olmadığını kontrol edin." },
      { title: "Bulaşık makinesi temiz yıkamıyor, lekeli veya kireçli bırakıyor", causes: "Tıkalı filtre, püskürtme kollarındaki deliklerin kireçle kapanması, yanlış yerleşim ve tuz ya da parlatıcı eksikliği en yaygın nedenlerdir. Su yeterince ısınmıyorsa rezistans, su hiç püskürtülmüyorsa yıkama motoru incelenir.", check: "Filtreyi temizleyin, püskürtme kollarının serbestçe döndüğünü ve deliklerinin açık olduğunu kontrol edin. Tuz ve parlatıcı hazneleri boşsa doldurun. Büyük kapların püskürtme kollarının dönüşünü engellemediğinden emin olun." },
      { title: "Bulaşık makinesinin altından su akıyor", causes: "Kapak contasının aşınması, hortum bağlantıları, pompa contası veya makine içinde aşırı köpük oluşması su kaçağına neden olur. Elde bulaşık deterjanının makinede kullanılması taşmaya kadar varan yoğun köpük yapar.", check: "Su yayılıyorsa musluğu kapatıp fişi kuru elle çekin. Yalnızca bulaşık makinesine uygun deterjan kullanıldığını ve kapak contasının yerinden çıkmadığını kontrol edin." },
      { title: "Bulaşık makinesinin kapağı tam kapanmıyor", causes: "Kapak kilit mandalının aşınması, menteşe yaylarının veya ipinin kopması ya da raf raylarının kapağa çarpması kapağın tam kapanmasını engeller. Kapak kapanmadığında makine programı başlatmaz veya yıkama sırasında durur.", check: "Üst ve alt sepetlerin raylarına tam oturduğunu, kapağa çarpan bir kap olmadığını kontrol edin. Kapağı zorlamayın; menteşe tarafında gevşeklik varsa kullanımı bırakın." },
    ],
    service: "Filtre, hortum ve kapak ayarı gibi işler genellikle aynı ziyarette tamamlanır. Tahliye pompası, yıkama motoru, rezistans, su giriş ventili veya kontrol kartı gerektiren arızalarda süre, modele ve parça temin durumuna göre değişir. Arızanın kaynağı ve ücret inceleme sonrası açıklanır; onayınız alınmadan parça değişimi yapılmaz.",
    urgent: "Tabanda sürekli su birikiyor, priz çevresinden yanık kokusu geliyor veya makine sigorta attırıyorsa kullanmayın ve musluğu kapatın. İçeride sıcak su ve buhar bulunduğu için program ortasında kapağı zorlayarak açmayın.",
  },
  "Fırın": {
    description: "Konya’da fırın ısıtmıyor, soğuk hava üflüyor, sigorta attırıyor ya da eşit pişirmiyorsa Eşli Teknik’e WhatsApp’tan yazın. Online servis takibi.",
    faults: [
      { title: "Fırın ısıtmıyor", causes: "Alt, üst veya fan rezistansının yanması, termostat ya da sıcaklık sensörü arızası ve aşırı ısınmaya karşı koruyan termik sigortanın atması en yaygın nedenlerdir. Dijital ekranlı birçok fırın, elektrik kesintisinden sonra saat ayarlanmadan ısıtmaya başlamaz.", check: "Ekranda saatin yanıp sönüp sönmediğine bakın; yanıp sönüyorsa saati ayarlayın. Çocuk kilidinin ve zamanlayıcının açık kalmadığını, fırın sigortasının inmediğini kontrol edin. Rezistans veya termostatı sökmeyin." },
      { title: "Fırın soğuk hava üflüyor, fan çalışıyor ama ısınmıyor", causes: "Turbo veya fanlı pişirme programlarında havayı ısıtan fan rezistansı arızalandığında fan döner ama hava ısınmaz. Diğer programlarda da ısınma yoksa termostat, termik veya kontrol kartı değerlendirilir.", check: "Alt-üst ısıtma gibi fansız bir programda ısınma olup olmadığını deneyin. Bu bilgi, arızanın fan rezistansında mı yoksa genel ısıtma sisteminde mi olduğunu ayırt etmeyi kolaylaştırır." },
      { title: "Fırın sigorta veya şartel attırıyor", causes: "Rezistansın çatlaması veya gövdeye kaçak yapması, nem almış bağlantılar ve hasarlı kablolar sigortanın atmasına neden olur. Sigorta genellikle belirli bir program seçildiğinde atıyorsa ilgili rezistans öne çıkar.", check: "Fırını tekrar tekrar çalıştırmayın. Sigortayı kaldırmadan önce fırının sigortasını kapalı tutun ve hangi program seçildiğinde attığını not edin." },
      { title: "Fırın eşit pişirmiyor, altını veya üstünü yakıyor", causes: "Seçilen programın yemeğe uygun olmaması, rezistanslardan birinin çalışmaması, termostatın gerçek sıcaklıktan sapması veya kapak contasının ısı kaçırması düzensiz pişirmeye yol açar.", check: "Tepsinin fırının ortasındaki rafta durduğunu ve doğru programın seçildiğini kontrol edin. Kapak kapalıyken contanın etrafından belirgin sıcak hava çıkıp çıkmadığına dikkat edin." },
      { title: "Fırın kendini kapatıyor ya da uyarı sesi veriyor", causes: "Aşırı ısınma durumunda termik koruma fırını kapatır. Gövdeyi soğutan fanın çalışmaması bu korumayı sık devreye sokar. Zamanlayıcıda süre ayarlanmışsa fırın süre dolunca durup uyarı verir.", check: "Zamanlayıcıda kurulu bir süre olup olmadığını kontrol edin. Pişirme sonrasında gövdeden gelen soğutma fanı sesinin kesilip kesilmediğini not edin." },
    ],
    service: "Saat ayarı, conta ve bağlantı kaynaklı sorunlar aynı ziyarette giderilebilir. Rezistans, termostat, fan motoru, termik veya kontrol kartı değişimi gereken durumlarda süre, fırının modeline ve parça temin durumuna göre değişir. İşlem kapsamı ve ücret inceleme sonrası açıklanır; onayınız olmadan parça değiştirilmez.",
    urgent: "Duman, yanık kokusu, kapak camında çatlak veya fırının dış gövdesinde aşırı ısınma varsa fırını kapatın ve sigortasını indirin. Gazlı modellerde gaz kokusu alırsanız vanayı kapatın, elektrik düğmelerine dokunmadan ortamı havalandırın ve cihazı kullanmayın.",
  },
  "Kurutma Makinesi": {
    description: "Konya’da kurutma makinesi kurutmuyor, nemli bırakıyor, su tankı uyarısı veriyor ya da dönmüyorsa Eşli Teknik’e WhatsApp’tan yazın. Online servis takibi.",
    faults: [
      { title: "Kurutma makinesi kurutmuyor, çamaşırları nemli bırakıyor", causes: "Tiftik filtresinin ve yoğuşturucunun tüyle tıkanması hava akışını keser ve kurutmayı zayıflatır. Aşırı yük, düşük kurutma seviyesi seçilmesi ve yumuşatıcı kalıntısıyla kaplanan nem sensörü de makinenin erken durmasına yol açar. Bu kontroller sorunsuzsa rezistans, termik veya ısı pompası sistemi incelenir.", check: "Tiftik filtresini her kurutmadan sonra temizleyin. Yoğuşturucu veya alt filtreyi kılavuza göre çıkarıp yıkayın. Tamburu yarısından fazla doldurmayın ve daha yüksek bir kurutma seviyesi seçerek deneyin." },
      { title: "Kurutma makinesi çok uzun sürüyor, programı bitirmiyor", causes: "Hava akışını kısıtlayan kirli filtreler, iyi sıkılmamış çamaşırlar ve soğuk ortam kurutma süresini uzatır. Nem sensörü çamaşırın kuruduğunu algılayamazsa program uzamaya devam eder.", check: "Çamaşırların çamaşır makinesinde yüksek devirde sıkıldığından emin olun. Filtreleri temizleyin ve makinenin bulunduğu ortamın havalandığını kontrol edin." },
      { title: "Kurutma makinesi su tankı boş ama dolu uyarısı veriyor", causes: "Su tankının yerine tam oturmaması, tank içindeki şamandıranın takılması ya da suyu tanka basan pompanın arızalanması bu uyarıya neden olur. Tahliye hortumu doğrudan gidere bağlıysa hortumun kıvrılması veya tıkanması da uyarıyı tetikler.", check: "Tankı çıkarıp tamamen boşaltın ve tık sesiyle yerine oturtun. Gidere bağlı bir hortum varsa bağlantı noktasında sıkışma olup olmadığına bakın." },
      { title: "Kurutma makinesi tamburu dönmüyor ya da yarıda duruyor", causes: "Tamburu çeviren kayışın kopması, kapak anahtarının kapıyı algılamaması, motor arızası veya aşırı ısınmaya karşı devreye giren termik koruma tamburun dönmemesine neden olur. Motor sesi gelip tambur dönmüyorsa kayış öne çıkar.", check: "Kapağın tam kapandığını kontrol edin. Makine uzun süre çalıştıktan sonra durduysa filtreleri temizleyip soğumasını bekleyin; sorun tekrar ediyorsa kullanımı bırakın." },
      { title: "Kurutma makinesi ses yapıyor ya da kötü kokuyor", causes: "Tambur keçelerinin ve rulmanların aşınması, kayış gergi makarası veya cepte unutulmuş metal parçalar ses yapar. Kötü koku genellikle temizlenmemiş filtre ve yoğuşturucudan ya da tankta bekleyen sudan kaynaklanır.", check: "Tamburda ve cepte unutulan cisim olup olmadığını kontrol edin. Filtreleri, yoğuşturucuyu ve su tankını temizleyin; ses yeni başladıysa ne zaman arttığını not edin." },
    ],
    service: "Filtre, yoğuşturucu ve su tankı kaynaklı sorunlar çoğunlukla aynı ziyarette giderilir. Kayış, rezistans, termik, nem sensörü, pompa, motor veya ısı pompası sistemindeki arızalarda süre, modele ve parça temin durumuna göre değişir. Yapılacak işlem ve ücret inceleme sonrası paylaşılır; onayınız olmadan parça değiştirilmez.",
    urgent: "Gövdeden aşırı ısı, duman ya da yanık kokusu geliyorsa programı durdurun, fişi çekin ve tamburdaki çamaşırları soğumaya bırakın. Tüy birikimi yangın riskini artırdığı için filtreler temizlenmeden makineyi çalıştırmayın.",
  },
  "Ocak": {
    description: "Konya’da ocak ateşlemiyor, sarı alevle yanıyor, çıt çıt ses yapıyor ya da gözü kendiliğinden sönüyorsa Eşli Teknik’e WhatsApp’tan yazın. Online servis takibi.",
    faults: [
      { title: "Ocak ateşlemiyor, çakmak çakıyor ama gaz yanmıyor", causes: "Ateşleme pillerinin bitmesi veya ateşleme modülünün kıvılcım üretmemesi, gözün altındaki elektrodun yağ ve taşan yemekle kirlenmesi, enjektörün tıkanması ya da gaz vanasının tam açılmaması en sık nedenlerdir. Bazı ankastre ocaklarda güvenlik supabı alevi algılayamazsa çakmak kıvılcım üretse de gaz kesilir.", check: "Ateşleme pillerini yenileyin ve göz başlıklarının tam oturduğunu kontrol edin. Elektrot ve göz çevresini kuru bir bezle nazikçe silin; yanıcı temizlik spreyi kullanmayın. Gaz tüpü kullanılıyorsa tüpün dolu olduğunu ve vananın açık olduğunu kontrol edin." },
      { title: "Ocak sarı veya turuncu alevle yanıyor, is ve karartı bırakıyor", causes: "Hava-gaz karışımının bozulması, enjektör veya karıştırıcı boru üzerindeki toz ve yağ birikimi, kirli gaz ya da ortamdaki nem sarı-turuncu alev ve is oluşumuna yol açar. Bu durumda tencere tabanı ve göz çevresi zamanla kararır; uzun süre giderilmezse yanma verimi düşer.", check: "Göz başlığını çıkarıp yağ ve yemek artıklarını yumuşak bir fırçayla temizleyin, temizlik sırasında gaz vanasını kapalı tutun. Ocağın bulunduğu mutfağın havalandığından emin olun. Alev rengi tüm gözlerde aynıysa gaz kalitesiyle, tek gözde ise o gözün başlığıyla ilgili olabilir." },
      { title: "Ocak çıt çıt sesi kesilmiyor, kıvılcım sürekli çakıyor", causes: "Düğmenin tam ateşleme konumuna gelmeden bırakılması, düğme veya mikro switch içine sıvı kaçması, nemli ortam ya da ateşleme modülündeki bir arıza kıvılcımın alev yandıktan sonra da durmadan çakmasına neden olur. Bu durumda ateşleme pilleri normalden hızlı tükenir.", check: "Düğmeyi tam olarak ateşleme konumuna getirip bıraktığınızda çıt sesinin kesilip kesilmediğini kontrol edin. Ocağın üzerine sıvı döküldüyse düğmeleri söküp temizlemeye çalışmadan kuru bir bezle yüzeyi silin. Sesin hangi gözde ve ne zaman başladığını not edin." },
      { title: "Ocağın bir gözü az yanıyor veya kendiliğinden sönüyor", causes: "Enjektörün veya karıştırıcı borunun kısmen tıkanması, gaz basıncının düşük olması ya da alev algılama sensörünün alevi zayıf algılaması bir gözün az alevle yanmasına veya bir süre sonra sönmesine yol açar. Rüzgâr veya taşan sıvı alevi söndürdüğünde de güvenlik supabı gazı otomatik keser.", check: "Sorunun tüm gözlerde mi yoksa tek bir gözde mi olduğunu kontrol edin; tüm gözlerde ise gaz besleme tarafı, tek gözde ise o gözün başlığı öne çıkar. Ocağın yakınında hava akımı yaratan açık bir pencere olup olmadığına bakın. Taşan yemeği hemen temizleyin." },
      { title: "Cam veya indüksiyon ocak hiç açılmıyor, dokunmatik tuşlar tepki vermiyor", causes: "Cam yüzeydeki nem, su damlası veya yağ lekesi dokunmatik tuşların algılamasını engelleyebilir. Bunun dışında güç kartı, dokunmatik panel bağlantısı veya sigorta arızası ocağın hiç açılmamasına neden olur. Çocuk kilidinin etkin kalması da tuşların tepki vermemesi gibi algılanabilir.", check: "Cam yüzeyi ve tuşların üzerini kuru, temiz bir bezle silip tekrar deneyin. Kullanım kılavuzuna bakarak çocuk kilidinin açık olup olmadığını kontrol edin. Ocağın bağlı olduğu sigortanın atmadığından emin olun." },
    ],
    service: "İnceleme sonrasında arızanın kaynağı ve yapılacak işlem size açıklanır; onayınız alınmadan parça değiştirilmez. Ateşleme pili, elektrot temizliği ve düğme ayarı gibi işler çoğunlukla aynı ziyarette tamamlanır. Enjektör, gaz valfi, ateşleme modülü, güç kartı veya cam yüzey değişimi gereken durumlarda süre, ocağın modeline ve parça temin durumuna göre değişir.",
    urgent: "Ocaktan gaz kokusu alıyorsanız ateşleme yapmayın, elektrik düğmelerine ve prizlere dokunmadan gaz vanasını kapatın, kapı ve pencereleri açarak ortamı havalandırın ve cihazı kullanmadan destek alın. Alev sık sık kendiliğinden sönüp gazın yanmadan devam etmesi ya da cam yüzeyde çatlak fark ederseniz ocağı kapatıp kullanmayı bırakın.",
  },
  "Elektrikli Süpürge": {
    description: "Konya’da süpürge çekmiyor, ıslık sesi çıkarıyor, kendi kendine duruyor ya da şarj tutmuyorsa Eşli Teknik’e WhatsApp’tan yazın. Online servis takibi.",
    faults: [
      { title: "Elektrikli süpürge çekmiyor veya emişi zayıf", causes: "Torbanın veya toz haznesinin dolu olması, filtrelerin tozla tıkanması, hortum ya da boru içinde tıkanıklık ve fırça başlığına dolanan saç ve iplikler emişi zayıflatır. Gövde veya hortum bağlantılarındaki çatlak ve gevşeklikler de hava kaçırarak emiş gücünü düşürür.", check: "Torbayı veya hazneyi boşaltıp filtreleri kılavuza göre temizleyin ya da değiştirin. Hortumu ışığa tutarak içinde tıkanıklık olup olmadığına bakın. Fırçalı başlığın altını çevirip tekerleklerin serbest döndüğünü kontrol edin." },
      { title: "Süpürge ıslık sesi veya tiz ses çıkarıyor", causes: "Tıkalı hortum ya da filtre nedeniyle hava akışının daralması, hasarlı bir conta veya gevşek boru bağlantısından hava sızması, motor kömürlerinin ya da rulmanların aşınması tiz ses ve ıslık sesine yol açar.", check: "Tüm boru ve hortum bağlantılarının sıkı takıldığını kontrol edin. Filtre ve torbayı temizleyip tekrar deneyin. Sesin hangi emiş gücü kademesinde arttığını not edin." },
      { title: "Süpürge kendi kendine duruyor veya kısa çalışıp kapanıyor", causes: "Aşırı ısınmaya karşı devreye giren termik koruma, dolu torba veya tıkalı filtre nedeniyle motorun zorlanması, kablo makarasının ya da güç düğmesinin arızalanması cihazın kendiliğinden durmasına neden olur.", check: "Torba ve filtreleri kontrol edip temizleyin, cihazı kapatıp bir süre soğumaya bırakın. Uzatma kablosu yerine doğrudan prize takarak deneyin." },
      { title: "Süpürge motor veya yanık kokusu yapıyor", causes: "Motor kömürlerinin aşınması, dolu torbanın hava akışını kısıtlayarak motoru zorlaması ya da fan bölgesine dolanan iplik ve saçların sürtünmesi kokuya yol açar.", check: "Kokuyu fark eder etmez cihazı kapatın, torba ve filtreleri kontrol edin, fırça başlığında dolanmış iplik veya saç olup olmadığına bakın." },
      { title: "Dikey/şarjlı süpürge şarj tutmuyor veya robot süpürge çevrimdışı görünüyor", causes: "Batarya hücrelerinin zamanla kapasite kaybetmesi, şarj kontaklarının kirlenmesi ya da adaptörün arızalanması şarjlı süpürgede kısa çalışma süresine yol açar. Robot süpürgede ise Wi-Fi bağlantısının kopması, router değişikliği veya uygulama güncellemesi cihazın çevrimdışı görünmesine neden olabilir.", check: "Şarj kontaklarını ve adaptör ucunu kuru bir bezle temizleyin. Robot süpürgeyi kılavuza göre yeniden başlatıp Wi-Fi ağına yeniden bağlamayı deneyin. Tam şarj sonrası kullanım süresini not edin." },
    ],
    service: "İnceleme sonrasında arızanın kaynağı ve yapılacak işlem açıklanır; onayınız alınmadan parça değiştirilmez. Filtre, torba ve conta kaynaklı sorunlar çoğunlukla aynı ziyarette giderilir. Motor, motor kömürü, kablo makarası, güç düğmesi veya batarya değişimi gereken durumlarda süre, modele ve parça temin durumuna göre değişir.",
    urgent: "Süpürgeden kıvılcım, duman veya belirgin yanık kokusu geliyorsa cihazı derhal kapatıp fişini çekin ve tekrar çalıştırmayın. Şarjlı süpürge veya robot süpürgenin bataryası şişmiş, deforme olmuş ya da şarj sırasında aşırı ısınıyorsa cihazı şarjdan ayırıp kullanmayı bırakın.",
  },
  "Davlumbaz": {
    description: "Konya’da davlumbaz çekmiyor, ses yapıyor, yağ-su akıtıyor ya da sigorta attırıyorsa Eşli Teknik’e WhatsApp’tan yazın. Online servis takibi.",
    faults: [
      { title: "Davlumbaz çekmiyor veya emişi zayıf", causes: "Yağ filtrelerinin yağ ve tozla tıkanması, karbon filtrenin ömrünü doldurması, baca klapesinin yağla yapışıp tam açılmaması ya da motor/fanın güç kaybetmesi emişi zayıflatır.", check: "Yağ filtrelerini kılavuza göre söküp sıcak suda bulaşık deterjanıyla yıkayın. Karbon filtre varsa ne zaman değiştirildiğini kontrol edin. Baca bağlantısının kıvrılmadığından ve klapenin serbest hareket ettiğinden emin olun." },
      { title: "Davlumbaz çok ses yapıyor veya vınlama sesi çıkarıyor", causes: "Fan pervanesine yapışan yağ ve toz dengesizliğe yol açar, motor rulmanlarının aşınması ya da gevşek montaj vidaları titreşim ve vınlama sesine neden olur. Dar veya kıvrımlı baca borusu da hava direncini artırıp ses yapabilir.", check: "Motoru ve fan pervanesini kendiniz sökmeyin. Montaj vidalarının gevşek olmadığını ve gövdenin duvara sıkı sabitlendiğini gözle kontrol edin. Sesin hangi emiş kademesinde belirginleştiğini not edin." },
      { title: "Davlumbaz kendi kendine çalışıyor veya düğmelere geç tepki veriyor", causes: "Dokunmatik veya basmalı kontrol panelindeki nem ve yağ birikimi, kontrol kartındaki bir arıza ya da gevşek buton bağlantısı davlumbazın kendiliğinden çalışmasına veya düğmelere geç yanıt vermesine neden olur.", check: "Kontrol panelinin üzerini kuru, yağsız bir bezle silin. Düğmelere basarken elinizin yağlı olmadığından emin olun. Sorunun hangi düğmede ve ne sıklıkla oluştuğunu not edin." },
      { title: "Davlumbaz yağ veya su damlatıyor", causes: "Yağ filtresinin doygunlaşması, filtre ile gövde arasındaki contanın tam oturmaması ya da baca bağlantısındaki yoğuşma suyu davlumbazın altından damlamasına yol açar.", check: "Yağ filtresini çıkarıp temizleyin ve yerine tam oturduğundan emin olun. Damlamanın filtre bölgesinden mi yoksa gövdenin başka bir noktasından mı geldiğini not edin." },
      { title: "Davlumbaz ışığı yanmıyor veya kapağı tam kapanmıyor", causes: "Işık için LED modülünün veya ampulün ömrünü tamamlaması, bağlantı ucunun gevşemesi ışığın yanmamasına neden olur. Sürgülü kapaklı modellerde ray üzerindeki yağ birikimi veya mekanizmanın aşınması kapağın tam kapanmasını engeller.", check: "Ampul/LED bağlantısının tam takılı olduğunu kontrol edin. Kapak rayını hafifçe temizleyip zorlamadan hareket ettirin. Işık düğmesinin farklı bir konumunu deneyin." },
    ],
    service: "Yapılacak işlem ve varsa parça ihtiyacı incelemeden sonra netleşir; onayınız olmadan parça değişimi yapılmaz. Filtre, conta ve panel temizliği kaynaklı sorunlar genellikle aynı ziyarette giderilir. Motor, fan, kontrol kartı, LED modülü veya kapak mekanizması değişimi gereken durumlarda süre, modele ve parça temin durumuna göre değişir.",
    urgent: "Gövdeden veya motordan yanık kokusu geliyorsa, davlumbaz sigorta attırıyorsa ya da fan aşırı ısınmışsa cihazı kapatıp fişini çekin ve soğumadan tekrar çalıştırmayın. Ocak üzerinde alev yükselirse davlumbazı ve ocağı kapatın; üzerini uygun bir örtüyle kapatmayı deneyin, suyla söndürmeye çalışmayın ve gerekirse itfaiyeyi arayın.",
  },
  "Derin Dondurucu": {
    description: "Konya’da derin dondurucu soğutmuyor, aşırı buz tutuyor, su akıtıyor ya da sürekli çalışıyorsa Eşli Teknik’e WhatsApp’tan yazın. Online servis takibi.",
    faults: [
      { title: "Derin dondurucu soğutmuyor veya dondurmuyor", causes: "Kompresörün çalışmaması veya rölesinin arızalanması, soğutma gazı devresinde bir kaçak, kapağın tam kapanmaması ya da termostatın yanlış ayarlanması soğutmanın zayıflamasına veya durmasına neden olur.", check: "Termostat ayarının yanlışlıkla değişmediğini kontrol edin. Kapağın tam kapandığından emin olun. Cihazın arkasında hava dolaşımı için boşluk bırakıldığını ve arka ızgaranın tozdan temiz olduğunu kontrol edin." },
      { title: "Derin dondurucu aşırı buz tutuyor, karlanıyor", causes: "Kapağın sık açılması veya tam kapanmaması içeriye nemli hava sokarak buzlanmayı artırır. No-frost modellerde defrost rezistansı, zamanlayıcı veya termik sigortanın arızalanması sürekli buz birikmesine yol açar; statik modellerde belirli miktarda karlanma normaldir.", check: "Kapak contasının arasına ince bir kağıt sıkıştırıp kapıyı kapatın; kağıt kolayca çekiliyorsa conta tam kapatmıyor olabilir. Cihazın bulunduğu ortamın çok nemli veya sıcak olmadığını kontrol edin." },
      { title: "Derin dondurucu sürekli çalışıyor, hiç durmuyor", causes: "Kapağın tam kapanmaması, cihazın çok sıcak veya güneş alan bir yerde durması, kondenserin tozla kaplanması ya da termostat sensörünün arızalanması kompresörün durmadan çalışmasına neden olur.", check: "Cihazın havalandırması iyi, serin bir yerde durduğunu kontrol edin. Arkadaki kondenser ızgarasını fişi çektikten sonra tozdan temizleyin. Kapağın üzerine ağır bir şey konup tam kapanmasını engellemediğinden emin olun." },
      { title: "Derin dondurucu su akıtıyor veya tabanında su birikiyor", causes: "Sandık tipi modellerde tahliye tapasının açık unutulması ya da tıkanması, çekmeceli/dikey modellerde iç arka duvardaki gider deliğinin buzla veya kirle tıkanması, defrost suyunun taşması su birikmesine yol açar.", check: "Sandık tipi modelde tahliye tapasının yerinde ve temiz olduğunu kontrol edin. Dikey modelde iç arka duvardaki gider deliğini kılavuza göre ılık suyla açmayı deneyin." },
      { title: "Derin dondurucu ses yapıyor, öter veya alarm veriyor", causes: "Fan pervanesine sürtünen buz parçaları veya kompresör takozlarının gevşemesi ses yapar; sıcaklık alarmı genellikle kapağın açık kalması, uzun elektrik kesintisi sonrası iç ısının yükselmesi ya da soğutmanın zayıflamasıyla tetiklenir.", check: "Cihazın duvara ve dolaplara değip değmediğini, düz zeminde durduğunu kontrol edin. Alarm veriyorsa ekrandaki kodu veya yanıp sönen ışığı not edin." },
    ],
    service: "Arızanın nedeni ve gereken işlem, inceleme tamamlandıktan sonra size aktarılır; parça değişimi yalnızca onayınızla yapılır. Conta, tahliye ve termostat ayarı kaynaklı sorunlar çoğunlukla aynı ziyarette giderilir. Kompresör, defrost sistemi veya soğutma devresindeki bir kaçağın onarımı gibi işlerde süre, kaçak tespitine ve parça temin durumuna göre değişir.",
    urgent: "Yanık kokusu, prizde ısınma veya sigorta attırma varsa cihazı prizden çekin ve kullanmayın. Soğutma belirgin şekilde azaldıysa içindeki ürünleri başka bir soğutucuya aktarmayı düşünün; kapağı gereksiz açmamak iç sıcaklığın daha yavaş yükselmesini sağlar.",
  },
  "Su Sebili": {
    description: "Konya’da su sebili soğutmuyor, su akıtıyor-taşırıyor, yosun tutuyor ya da sigorta attırıyorsa Eşli Teknik’e WhatsApp’tan yazın. Online servis takibi.",
    faults: [
      { title: "Su sebili soğutmuyor", causes: "Kompresörlü sebillerde kompresör veya gaz devresi arızası, elektronik soğutuculu modellerde soğutucu modülün ömrünü tamamlaması, ortam sıcaklığının çok yüksek olması ya da havalandırma boşluklarının kapalı kalması soğutmayı zayıflatır.", check: "Cihazın arkasındaki havalandırma boşluklarının duvara veya dolaba yapışık kalmadığından emin olun. Sebili çok sıcak veya güneş alan bir yerden uzak tutun. Soğutma düğmesinin açık konumda olduğunu kontrol edin." },
      { title: "Su sebili su akıtıyor veya taşırıyor", causes: "Damacananın ters takılması veya ağız contasının aşınması, iç hazneye su dolumunu kesen şamandıra biriminin arızalanması, alttan damacanalı modellerde pompa veya boru bağlantısındaki bir sızıntı su taşmasına ya da akıtmasına yol açar.", check: "Damacananın ağız contasının sağlam ve tam oturduğunu kontrol edin. Damacanayı yerleştirirken cihazı sarsmayın. Taşan suyu hemen kurulayıp elektrik bağlantısına su temas etmediğinden emin olun." },
      { title: "Su sebili su vermiyor veya musluktan su gelmiyor", causes: "Damacananın boş olması veya ağzının tam açılmaması, alttan damacanalı modellerde pompanın veya emme hortumunun hava yapması, musluk mekanizmasının kireçle tıkanması su akışını keser.", check: "Damacanada yeterli su olduğunu ve ağız kapağının tam açıldığını kontrol edin. Musluğu birkaç kez çalıştırıp hava boşalmasını bekleyin. Musluk çıkışında kireç birikimi olup olmadığına bakın." },
      { title: "Su sebili yosun tutuyor veya koku yapıyor", causes: "İç haznenin ve musluk kanallarının düzenli temizlenmemesi, güneş ışığı alan bir yerde durması ya da uzun süre aynı suyun bekletilmesi yosun oluşumuna ve kötü kokuya yol açar.", check: "Kılavuzda önerilen aralıklarla iç hazneyi ve musluk ağızlarını temizleyin. Sebili doğrudan güneş almayan bir yere yerleştirin. Uzun süre kullanılmayacaksa damacanayı boşaltıp hazneyi kurutun." },
      { title: "Su sebili sigorta attırıyor veya ses çıkarıyor", causes: "Soğutma biriminin veya ısıtıcı rezistansın kaçak yapması, nem almış elektrik bağlantıları sigortanın atmasına neden olur. Kompresörlü modellerde takoz gevşemesi ses yapar; termostat arızası aşırı soğutup buz tutmasına yol açabilir.", check: "Sebili tekrar tekrar çalıştırmayın; fişi çekili tutup hangi düğmeye basıldığında sigorta attığını not edin. Cihazın düz ve sabit bir zeminde durduğunu kontrol edin." },
    ],
    service: "İnceleme bitince sorunun kaynağını ve yapılacak işlemi açıklarız; onay vermediğiniz hiçbir parça değiştirilmez. Damacana contası, musluk ve temizlik kaynaklı sorunlar genellikle aynı ziyarette giderilir. Kompresör, soğutucu modül, pompa, şamandıra veya ısıtıcı rezistans değişimi gereken durumlarda süre, modele ve parça temin durumuna göre değişir.",
    urgent: "Sıcak su veren modellerde rezistans bölgesinden yanık kokusu, priz çevresinde ısınma veya sigorta attırma varsa sebili prizden çekin ve kullanmayın. Elektrik bağlantısının bulunduğu bölgeye su döküldüyse cihazı kurulamadan ve kuru elle fişi çekmeden çalıştırmayın.",
  },
};
