/**
 * Cihaz arıza rehberi — hizmet sayfalarında (React) ve önceden render edilen SEO HTML'inde
 * (scripts/prerender.ts) aynı kaynaktan kullanılır.
 *
 * Kaynak: Google otomatik tamamlama ve "Diğer sorular" verilerinde öne çıkan gerçek arıza aramaları
 * (Eylül 2026) ile Eşli Teknik'in Google yorumlarında geçen işler. Metinler özgündür; fiyat,
 * süre garantisi veya yetkili servis iddiası içermez.
 */

export type DeviceFault = { title: string; causes: string; check: string };
export type DeviceFaultGuide = { description: string; faults: DeviceFault[] };

export const deviceFaultGuides: Record<string, DeviceFaultGuide> = {
  "Çamaşır Makinesi": {
    description: "Konya’da çamaşır makinesi su almıyor, boşaltmıyor, sıkmıyor ya da sesli çalışıyorsa Eşli Teknik’e WhatsApp’tan yazın. Online servis takibi.",
    faults: [
      { title: "Çamaşır makinesi su almıyor", causes: "Musluk veya şebeke basıncı, su giriş hortumundaki süzgecin kireç ve tortuyla tıkanması, su giriş ventili, kapak kilidinin kapalı olduğunu algılamaması ya da kontrol kartı bu belirtiye yol açabilir. Makine su almadan uğulduyor veya bekliyorsa ventil ve kilit tarafı öne çıkar.", check: "Musluğun sonuna kadar açık olduğunu, evin diğer musluklarında su bulunduğunu ve giriş hortumunun kıvrılmadığını kontrol edin. Kapağı sıkıca kapatıp programı yeniden başlatın. Hortum süzgecini yalnızca musluk kapalıyken ve kullanım kılavuzundaki adımlarla temizleyin." },
      { title: "Çamaşır makinesi suyu boşaltmıyor, içinde su kalıyor", causes: "En sık neden, pompa filtresine kaçan bozuk para, düğme, çorap veya tüy birikimidir. Tahliye hortumunun kıvrılması, lavabo sifonunun tıkanması ya da tahliye pompasının arızalanması da suyun içeride kalmasına neden olur. Pompa çalışırken ses gelip su çıkmıyorsa tıkanıklık, hiç ses gelmiyorsa pompa veya bağlantısı incelenir.", check: "Sıcak yıkamadan hemen sonra filtreyi açmayın; suyun soğumasını bekleyin. Önüne havlu ve düz bir kap koyarak ön alt kapaktaki filtreyi kılavuza göre açıp temizleyin. Tahliye hortumunun kıvrık olmadığını ve sifon bağlantısının açık olduğunu kontrol edin." },
      { title: "Çamaşır makinesi sıkma yapmıyor, sıkmaya geçmiyor", causes: "Makine içindeki suyu boşaltamıyorsa sıkmaya geçmez; bu yüzden önce tahliye kontrol edilir. Tek bir ağır parça (battaniye, paspas) yükü dengesizleştirip sıkmayı durdurabilir. Tahliye ve yük dengesi sorunsuzsa motor kömürleri, takometre, motor veya kontrol kartı değerlendirilir.", check: "Çamaşırları tamburun içinde dağıtın ya da birkaç parça daha ekleyerek yükü dengeleyin. Sıkma devri kapalı veya çok düşük bir program seçilmediğinden emin olun. Kısa bir sıkma programını az yükle deneyin." },
      { title: "Sıkmada aşırı sallanma, yürüme ve ses", causes: "Dengesiz yük ve düzgün olmayan zemin en yaygın nedenlerdir. Yeni kurulan makinede nakliye cıvatalarının sökülmemesi şiddetli sarsıntı yapar. Sorun devam ediyorsa amortisörler, askı yayları veya kazan rulmanı incelenir; sıkmada artan uğultu ve metalik ses genellikle rulman ve keçe grubuna işaret eder.", check: "Makinenin ayaklarını ayarlayıp dört köşenin zemine eşit bastığını kontrol edin. Yeni kurulumda arka taraftaki nakliye cıvatalarının çıkarıldığından emin olun. Tamburu elle çevirip içeride sıkışmış metal bir cisim olup olmadığına bakın." },
      { title: "Çamaşır makinesi altından su akıtıyor", causes: "Giriş veya tahliye hortumu bağlantıları, deterjan çekmecesinde taşma, kapak körüğündeki yırtık ya da sıkışmış küçük parçalar ve pompa contası su kaçağının başlıca kaynaklarıdır. Suyun yıkamanın hangi aşamasında aktığı, kaynağın bulunmasına yardım eder.", check: "Su yayılıyorsa önce musluğu kapatın ve fişi kuru elle çekin. Hortum bağlantılarını, deterjan çekmecesini ve kapak körüğünü gözle kontrol edin. Elde yıkama deterjanı kullanmak aşırı köpük ve taşma yapabilir." },
      { title: "Çamaşır makinesi sigorta attırıyor", causes: "Isıtıcı rezistansta kaçak, motor veya kablo hasarı ve nem alan elektrik bağlantıları sigortanın atmasına neden olur. Sigorta genellikle ısıtma veya sıkma aşamasında atıyorsa arızanın yeri buna göre daraltılır.", check: "Makineyi tekrar tekrar çalıştırmayın ve farklı prizlerde denemeyin. Fişi çekili tutun; hangi aşamada sigorta attığını not edip servis talebinizde paylaşın." },
    ],
  },
  "Buzdolabı": {
    description: "Konya’da buzdolabı soğutmuyor, buzlanıyor, su akıtıyor ya da sesli çalışıyorsa Eşli Teknik’e WhatsApp’tan yazın. Online servis takibi.",
    faults: [
      { title: "Buzdolabı çalışıyor ama soğutmuyor", causes: "Işık yanıyor ve motor sesi geliyor ama iç ısınıyorsa fan motoru, hava kanalındaki buz tıkanıklığı, sıcaklık sensörü, defrost sistemi ya da kompresör ve rölesi incelenir. Soğutma gazı kendiliğinden bitmez; gaz eksikliği ancak bir kaçak varsa oluşur ve kaçak bulunmadan yapılan dolum kalıcı çözüm değildir.", check: "Sıcaklık ayarının yanlışlıkla değişmediğini, kapının tam kapandığını ve dolabın arkasında hava dolaşımı için boşluk kaldığını kontrol edin. Arka ızgarayı fişi çektikten sonra tozdan arındırın. İçeriye sıcak yemek konulduysa soğutmanın toparlanması birkaç saat sürebilir." },
      { title: "Buzdolabının altı soğutmuyor, dondurucu soğutuyor", causes: "No-frost buzdolaplarında soğuk hava dondurucudan bir kanal ve fan aracılığıyla alt bölmeye taşınır. Bu kanal buzla tıkanırsa, fan çalışmazsa ya da hava akışını ayarlayan kapakçık arızalanırsa dondurucu soğuk kalırken alt bölme ısınır. Sorunun kökü genellikle defrost sistemidir.", check: "Alt bölmenin arka duvarındaki hava çıkışlarını ürünlerin kapatmadığından emin olun. Dondurucunun arka duvarında kalın bir buz tabakası varsa bunu servis talebinizde belirtin. Buzu bıçak veya sivri bir aletle kazımayın." },
      { title: "Buzdolabı buzlanma ve karlanma yapıyor", causes: "Kapı contasının tam oturmaması, kapının sık ve uzun açılması içeriye nemli hava alır ve buzlanma yapar. No-frost modellerde sürekli buzlanma defrost rezistansı, termik koruma veya zamanlayıcı arızasına işaret eder.", check: "Contanın arasına bir kağıt sıkıştırıp kapıyı kapatın; kağıt kolayca kayıyorsa conta tam kapatmıyor olabilir. Kapının ürünlere çarpmadan tam kapandığını kontrol edin." },
      { title: "Buzdolabı su akıtıyor, içinde su birikiyor", causes: "Alt bölmenin arka duvarındaki gider deliği tıkanırsa eriyen su dışarı atılamaz ve rafların altında birikir. Buzdolabının öne doğru eğimli durması veya dondurucudan gelen su kanalının buzlanması da su akıtmaya neden olur.", check: "Arka duvardaki gider deliğini kullanım kılavuzunda anlatılan şekilde ılık suyla açın. Dolabın hafifçe arkaya eğimli ve sabit durduğunu kontrol edin." },
      { title: "Buzdolabı sesli çalışıyor ya da hiç durmadan çalışıyor", causes: "Fan pervanesine buz sürtünmesi, kompresör takozlarının gevşemesi veya dolabın düz olmayan zeminde durması belirgin ses yapar. Sürekli çalışma ise conta sızıntısı, kirli kondenser, çok sıcak ortam ya da sıcaklık sensörüyle ilgili olabilir. Kısa tıklamalar ve akış sesleri normal çalışma sesleridir.", check: "Dolabın duvara ve dolaplara değmediğini, ayaklarının sağlam bastığını kontrol edin. Sesin kapı açıkken değişip değişmediğini not edin; bu, fan kaynaklı sesi ayırt etmeye yardım eder." },
    ],
  },
  "Bulaşık Makinesi": {
    description: "Konya’da bulaşık makinesi su almıyor, boşaltmıyor, temiz yıkamıyor ya da su akıtıyorsa Eşli Teknik’e WhatsApp’tan yazın. Online servis takibi.",
    faults: [
      { title: "Bulaşık makinesi su almıyor, yıkamaya geçmiyor", causes: "Kapalı musluk, giriş hortumundaki süzgecin tıkanması, su giriş ventili veya su taşma korumasının devreye girmesi makinenin su almamasına yol açar. Kapak tam kapanmadığında makine güvenlik nedeniyle programı başlatmaz. Makine su alıyor ama yıkamaya geçmiyorsa yıkama motoru, ısıtıcı veya kontrol kartı değerlendirilir.", check: "Musluğun açık ve hortumun kıvrılmamış olduğunu kontrol edin. Kapağın tık sesiyle tam kapandığından emin olun. Taban bölgesinden su sızıntısı varsa makine kendini korumaya alabilir; bu durumu servis talebinizde belirtin." },
      { title: "Bulaşık makinesi suyu boşaltmıyor, dipte su kalıyor", causes: "Makine tabanındaki filtrenin yemek artığıyla tıkanması en sık nedendir. Tahliye hortumunun kıvrılması, lavabo sifonuna bağlantı noktasının tıkanması ya da tahliye pompasının arızalanması da suyun dipte kalmasına neden olur.", check: "Alt sepeti çıkarıp tabandaki filtreyi kılavuza göre söküp temizleyin. Tahliye hortumunun kıvrık olmadığını ve sifon bağlantısının açık olduğunu kontrol edin." },
      { title: "Bulaşık makinesi temiz yıkamıyor, lekeli veya kireçli bırakıyor", causes: "Tıkalı filtre, püskürtme kollarındaki deliklerin kireçle kapanması, yanlış yerleşim ve tuz ya da parlatıcı eksikliği en yaygın nedenlerdir. Su yeterince ısınmıyorsa rezistans, su hiç püskürtülmüyorsa yıkama motoru incelenir.", check: "Filtreyi temizleyin, püskürtme kollarının serbestçe döndüğünü ve deliklerinin açık olduğunu kontrol edin. Tuz ve parlatıcı hazneleri boşsa doldurun. Büyük kapların püskürtme kollarının dönüşünü engellemediğinden emin olun." },
      { title: "Bulaşık makinesinin altından su akıyor", causes: "Kapak contasının aşınması, hortum bağlantıları, pompa contası veya makine içinde aşırı köpük oluşması su kaçağına neden olur. Elde bulaşık deterjanının makinede kullanılması taşmaya kadar varan yoğun köpük yapar.", check: "Su yayılıyorsa musluğu kapatıp fişi kuru elle çekin. Yalnızca bulaşık makinesine uygun deterjan kullanıldığını ve kapak contasının yerinden çıkmadığını kontrol edin." },
      { title: "Bulaşık makinesinin kapağı tam kapanmıyor", causes: "Kapak kilit mandalının aşınması, menteşe yaylarının veya ipinin kopması ya da raf raylarının kapağa çarpması kapağın tam kapanmasını engeller. Kapak kapanmadığında makine programı başlatmaz veya yıkama sırasında durur.", check: "Üst ve alt sepetlerin raylarına tam oturduğunu, kapağa çarpan bir kap olmadığını kontrol edin. Kapağı zorlamayın; menteşe tarafında gevşeklik varsa kullanımı bırakın." },
    ],
  },
  "Fırın": {
    description: "Konya’da fırın ısıtmıyor, soğuk hava üflüyor, sigorta attırıyor ya da eşit pişirmiyorsa Eşli Teknik’e WhatsApp’tan yazın. Online servis takibi.",
    faults: [
      { title: "Fırın ısıtmıyor", causes: "Alt, üst veya fan rezistansının yanması, termostat ya da sıcaklık sensörü arızası ve aşırı ısınmaya karşı koruyan termik sigortanın atması en yaygın nedenlerdir. Dijital ekranlı birçok fırın, elektrik kesintisinden sonra saat ayarlanmadan ısıtmaya başlamaz.", check: "Ekranda saatin yanıp sönüp sönmediğine bakın; yanıp sönüyorsa saati ayarlayın. Çocuk kilidinin ve zamanlayıcının açık kalmadığını, fırın sigortasının inmediğini kontrol edin. Rezistans veya termostatı sökmeyin." },
      { title: "Fırın soğuk hava üflüyor, fan çalışıyor ama ısınmıyor", causes: "Turbo veya fanlı pişirme programlarında havayı ısıtan fan rezistansı arızalandığında fan döner ama hava ısınmaz. Diğer programlarda da ısınma yoksa termostat, termik veya kontrol kartı değerlendirilir.", check: "Alt-üst ısıtma gibi fansız bir programda ısınma olup olmadığını deneyin. Bu bilgi, arızanın fan rezistansında mı yoksa genel ısıtma sisteminde mi olduğunu ayırt etmeyi kolaylaştırır." },
      { title: "Fırın sigorta veya şartel attırıyor", causes: "Rezistansın çatlaması veya gövdeye kaçak yapması, nem almış bağlantılar ve hasarlı kablolar sigortanın atmasına neden olur. Sigorta genellikle belirli bir program seçildiğinde atıyorsa ilgili rezistans öne çıkar.", check: "Fırını tekrar tekrar çalıştırmayın. Sigortayı kaldırmadan önce fırının sigortasını kapalı tutun ve hangi program seçildiğinde attığını not edin." },
      { title: "Fırın eşit pişirmiyor, altını veya üstünü yakıyor", causes: "Seçilen programın yemeğe uygun olmaması, rezistanslardan birinin çalışmaması, termostatın gerçek sıcaklıktan sapması veya kapak contasının ısı kaçırması düzensiz pişirmeye yol açar.", check: "Tepsinin fırının ortasındaki rafta durduğunu ve doğru programın seçildiğini kontrol edin. Kapak kapalıyken contanın etrafından belirgin sıcak hava çıkıp çıkmadığına dikkat edin." },
      { title: "Fırın kendini kapatıyor ya da uyarı sesi veriyor", causes: "Aşırı ısınma durumunda termik koruma fırını kapatır. Gövdeyi soğutan fanın çalışmaması bu korumayı sık devreye sokar. Zamanlayıcıda süre ayarlanmışsa fırın süre dolunca durup uyarı verir.", check: "Zamanlayıcıda kurulu bir süre olup olmadığını kontrol edin. Pişirme sonrasında gövdeden gelen soğutma fanı sesinin kesilip kesilmediğini not edin." },
    ],
  },
  "Kurutma Makinesi": {
    description: "Konya’da kurutma makinesi kurutmuyor, nemli bırakıyor, su tankı uyarısı veriyor ya da dönmüyorsa Eşli Teknik’e WhatsApp’tan yazın. Online servis takibi.",
    faults: [
      { title: "Kurutma makinesi kurutmuyor, çamaşırları nemli bırakıyor", causes: "Tiftik filtresinin ve yoğuşturucunun tüyle tıkanması hava akışını keser ve kurutmayı zayıflatır. Aşırı yük, düşük kurutma seviyesi seçilmesi ve yumuşatıcı kalıntısıyla kaplanan nem sensörü de makinenin erken durmasına yol açar. Bu kontroller sorunsuzsa rezistans, termik veya ısı pompası sistemi incelenir.", check: "Tiftik filtresini her kurutmadan sonra temizleyin. Yoğuşturucu veya alt filtreyi kılavuza göre çıkarıp yıkayın. Tamburu yarısından fazla doldurmayın ve daha yüksek bir kurutma seviyesi seçerek deneyin." },
      { title: "Kurutma makinesi çok uzun sürüyor, programı bitirmiyor", causes: "Hava akışını kısıtlayan kirli filtreler, iyi sıkılmamış çamaşırlar ve soğuk ortam kurutma süresini uzatır. Nem sensörü çamaşırın kuruduğunu algılayamazsa program uzamaya devam eder.", check: "Çamaşırların çamaşır makinesinde yüksek devirde sıkıldığından emin olun. Filtreleri temizleyin ve makinenin bulunduğu ortamın havalandığını kontrol edin." },
      { title: "Kurutma makinesi su tankı boş ama dolu uyarısı veriyor", causes: "Su tankının yerine tam oturmaması, tank içindeki şamandıranın takılması ya da suyu tanka basan pompanın arızalanması bu uyarıya neden olur. Tahliye hortumu doğrudan gidere bağlıysa hortumun kıvrılması veya tıkanması da uyarıyı tetikler.", check: "Tankı çıkarıp tamamen boşaltın ve tık sesiyle yerine oturtun. Tahliye hortumu bağlıysa kıvrılmadığını kontrol edin." },
      { title: "Kurutma makinesi tamburu dönmüyor ya da yarıda duruyor", causes: "Tamburu çeviren kayışın kopması, kapak anahtarının kapıyı algılamaması, motor arızası veya aşırı ısınmaya karşı devreye giren termik koruma tamburun dönmemesine neden olur. Motor sesi gelip tambur dönmüyorsa kayış öne çıkar.", check: "Kapağın tam kapandığını kontrol edin. Makine uzun süre çalıştıktan sonra durduysa filtreleri temizleyip soğumasını bekleyin; sorun tekrar ediyorsa kullanımı bırakın." },
      { title: "Kurutma makinesi ses yapıyor ya da kötü kokuyor", causes: "Tambur keçelerinin ve rulmanların aşınması, kayış gergi makarası veya cepte unutulmuş metal parçalar ses yapar. Kötü koku genellikle temizlenmemiş filtre ve yoğuşturucudan ya da tankta bekleyen sudan kaynaklanır.", check: "Tamburda ve cepte unutulan cisim olup olmadığını kontrol edin. Filtreleri, yoğuşturucuyu ve su tankını temizleyin; ses yeni başladıysa ne zaman arttığını not edin." },
    ],
  },
};
