/**
 * Yasal sayfaların (KVKK, Gizlilik, Çerez) metni — React sayfası (ContentPage) ve prerender HTML'i bu tek kaynaktan beslenir.
 * Metin değişikliği hukuki içeriktir; proje sahibinin onayı olmadan değiştirme.
 */
export type LegalSection = { title: string; paragraphs?: string[]; items?: string[]; after?: string; contact?: string[] };

export const kvkkSections: LegalSection[] = [
    { title: "Veri Sorumlusu", paragraphs: ["6698 sayılı Kişisel Verilerin Korunması Kanunu (\"KVKK\") kapsamında kişisel verileriniz, veri sorumlusu sıfatıyla Eşli Teknik tarafından işlenmektedir."], contact: ["Yetkili: Mevlüt Esad EŞLİ", "Telefon: 0 551 185 87 73", "E-posta: bilgi@esliteknik.com"] },
    { title: "İşlenen Kişisel Veriler", paragraphs: ["Web sitemiz ve iletişim kanallarımız üzerinden bizimle iletişime geçmeniz halinde aşağıdaki kişisel verileriniz işlenebilmektedir:"], items: ["Ad ve soyad bilgisi", "Telefon numarası", "WhatsApp iletişim bilgileri", "Servis talebiniz ile ilgili açıklamalar", "Servis hizmetinin gerçekleştirileceği adres bilgisi", "İletişim süreçlerine ilişkin bilgiler"] },
    { title: "Kişisel Verilerin İşlenme Amaçları", paragraphs: ["Kişisel verileriniz aşağıdaki amaçlarla işlenmektedir:"], items: ["Teknik servis talebinizin alınması", "Beyaz eşya arıza bildiriminizin değerlendirilmesi", "Sizinle iletişim kurulması", "Servis hizmetinin planlanması", "Teknisyen yönlendirilmesi", "Müşteri memnuniyetinin sağlanması", "Hizmet süreçlerinin yürütülmesi", "Yasal yükümlülüklerin yerine getirilmesi"] },
    { title: "Kişisel Verilerin Toplanma Yöntemi ve Hukuki Sebebi", paragraphs: ["Kişisel verileriniz aşağıdaki iletişim kanalları aracılığıyla elektronik ortamda veya sözlü olarak toplanabilmektedir:"], items: ["Web sitemizde yer alan iletişim kanalları", "WhatsApp iletişim hattı", "Telefon görüşmeleri"], after: "Kişisel verileriniz; bir sözleşmenin kurulması veya ifasıyla doğrudan ilgili olması, veri sorumlusunun hukuki yükümlülüklerini yerine getirmesi ve veri sorumlusunun meşru menfaatleri hukuki sebeplerine dayanılarak işlenmektedir." },
    { title: "Kişisel Verilerin Aktarılması", paragraphs: ["Kişisel verileriniz; teknik servis hizmetinin gerçekleştirilebilmesi amacıyla Eşli Teknik bünyesinde görev yapan yetkili personel ile ve kanunen yetkili kamu kurum ve kuruluşları ile mevzuata uygun şekilde paylaşılabilir."] },
    { title: "Kişisel Verilerin Saklanması", paragraphs: ["Kişisel verileriniz, işlenme amacı için gerekli süre boyunca ve ilgili mevzuatta öngörülen saklama süreleri dikkate alınarak muhafaza edilir.", "Saklama süresinin sona ermesi halinde kişisel verileriniz silinir, yok edilir veya anonim hale getirilir."] },
    { title: "İlgili Kişinin Hakları", paragraphs: ["KVKK'nın 11. maddesi kapsamında kişisel verilerinizle ilgili olarak aşağıdaki haklara sahipsiniz:"], items: ["Kişisel verilerinizin işlenip işlenmediğini öğrenme", "İşlenmişse buna ilişkin bilgi talep etme", "İşlenme amacını ve amaca uygun kullanılıp kullanılmadığını öğrenme", "Aktarıldığı üçüncü kişileri bilme", "Eksik veya yanlış işlenmişse düzeltilmesini isteme", "Kanuni şartlar oluştuğunda silinmesini veya yok edilmesini isteme", "İşlenen verilerin münhasıran otomatik sistemler ile analiz edilmesi sonucunda aleyhinize bir sonuç ortaya çıkmasına itiraz etme", "Kanuna aykırı işlenmesi sebebiyle zarara uğramanız halinde zararınızın giderilmesini talep etme"] },
    { title: "Başvuru", paragraphs: ["KVKK kapsamındaki taleplerinizi Eşli Teknik'e yazılı olarak veya mevzuatta belirtilen diğer yöntemlerle iletebilirsiniz.", "Başvurularınız ilgili mevzuat kapsamında değerlendirilerek sonuçlandırılır."] }
];

export const privacySections: LegalSection[] = [
    {title:"Genel Bilgilendirme",paragraphs:["Eşli Teknik olarak ziyaretçilerimizin ve müşterilerimizin gizliliğine önem vermekteyiz.","Bu Gizlilik Politikası, www.esliteknik.com internet sitesini ziyaret eden kullanıcıların gizliliğinin korunması, internet sitesi kullanım süreçleri ve kullanıcı bilgilerinin nasıl değerlendirildiği hakkında bilgi vermek amacıyla hazırlanmıştır.","Web sitemizi ziyaret ederek veya iletişim kanallarımız aracılığıyla bizimle iletişime geçerek bu Gizlilik Politikası'nda belirtilen uygulamaları kabul etmiş olursunuz."]},
    {title:"Toplanan Bilgiler",paragraphs:["Web sitemizi ziyaret ettiğinizde veya Eşli Teknik ile iletişime geçtiğinizde aşağıdaki bilgiler işlenebilmektedir:"],items:["Ad ve soyad bilgisi","Telefon numarası","WhatsApp iletişim bilgileri","Servis talebiniz ile ilgili açıklamalar","Hizmet adresi bilgileri","Web sitesinin kullanımına ilişkin teknik bilgiler"],after:"Kullanıcılarımızdan yalnızca sunulan teknik servis hizmetlerinin yürütülmesi için gerekli olan bilgiler talep edilmektedir."},
    {title:"Bilgilerin Kullanım Amaçları",paragraphs:["Toplanan bilgiler aşağıdaki amaçlarla kullanılmaktadır:"],items:["Teknik servis taleplerinin alınması","Kullanıcılarla iletişim kurulması","Arıza bildiriminin değerlendirilmesi","Servis hizmetinin planlanması","Teknisyen yönlendirilmesi","Müşteri memnuniyetinin sağlanması","Hizmet kalitesinin geliştirilmesi","Yasal yükümlülüklerin yerine getirilmesi"]},
    {title:"WhatsApp İletişimi Hakkında",paragraphs:["Web sitemizde yer alan WhatsApp iletişim bağlantısı üzerinden bizimle iletişime geçebilirsiniz.","WhatsApp üzerinden tarafımıza ilettiğiniz bilgiler, servis talebinizin değerlendirilmesi ve teknik servis hizmetinin sağlanması amacıyla kullanılmaktadır.","WhatsApp hizmeti, üçüncü taraf bir iletişim platformu tarafından sağlanmaktadır. Bu platform üzerinden gerçekleştirilen iletişimlerde ilgili platformun kendi gizlilik politikaları da geçerlidir."]},
    {title:"Kişisel Bilgilerin Korunması",paragraphs:["Eşli Teknik, kullanıcı bilgilerinin güvenliğini sağlamak amacıyla gerekli teknik ve idari tedbirleri almaktadır."],items:["Yetkisiz erişime karşı korunur","Hizmet amacı dışında kullanılmaz","Kanuni zorunluluklar dışında üçüncü kişilerle paylaşılmaz"]},
    {title:"Bilgilerin Paylaşılması",paragraphs:["Kullanıcı bilgileriniz aşağıdaki kişi ve kuruluşlarla mevzuata uygun şekilde paylaşılabilir:"],items:["Teknik servis hizmetinin gerçekleştirilebilmesi için yetkili Eşli Teknik personeliyle","Kanunen yetkili kamu kurum ve kuruluşlarıyla","Hizmetin yerine getirilmesi için gerekli olması halinde ilgili hizmet sağlayıcılarla"],after:"Kişisel bilgileriniz hiçbir şekilde satılmaz veya ticari amaçlarla üçüncü kişilere aktarılmaz."},
    {title:"Web Sitesi Kullanımı ve Teknik Veriler",paragraphs:["Web sitemizi ziyaret ettiğinizde IP adresi, tarayıcı bilgileri, ziyaret zamanı ve ziyaret edilen sayfalar gibi teknik veriler güvenlik, performans ölçümü ve kullanıcı deneyiminin geliştirilmesi amacıyla işlenebilir.","Bu bilgiler, kullanıcı kimliğini doğrudan belirlemek amacıyla kullanılmaz."]},
    {title:"Çerezler (Cookies)",paragraphs:["Web sitemizde kullanıcı deneyimini geliştirmek, sitenin güvenli ve etkin şekilde çalışmasını sağlamak amacıyla çerezlerden yararlanılabilir.","Çerez kullanımı hakkında ayrıntılı bilgi için Çerez Politikası metnimizi inceleyebilirsiniz."]},
    {title:"Üçüncü Taraf Bağlantıları",paragraphs:["Web sitemizde kullanıcıların faydalanması amacıyla üçüncü taraf platformlara yönlendiren bağlantılar bulunabilir.","Bu bağlantılar üzerinden erişilen internet sitelerinin gizlilik uygulamalarından Eşli Teknik sorumlu değildir. Kullanıcıların, ziyaret ettikleri üçüncü taraf internet sitelerinin gizlilik politikalarını incelemeleri önerilir."]},
    {title:"Politika Değişiklikleri",paragraphs:["Eşli Teknik, gerekli gördüğü durumlarda bu Gizlilik Politikası üzerinde değişiklik yapabilir.","Güncellenen politika, www.esliteknik.com adresinde yayınlandığı tarihten itibaren geçerli olur."]},
    {title:"İletişim",paragraphs:["Gizlilik Politikası hakkında sorularınız veya talepleriniz için aşağıdaki iletişim kanallarından bizimle iletişime geçebilirsiniz."],contact:["Eşli Teknik / Mevlüt Esad EŞLİ","Telefon: 0 551 185 87 73","E-posta: bilgi@esliteknik.com","Web: www.esliteknik.com"]}
];

export const cookieSections: LegalSection[] = [
    {title:"Çerez Nedir?",paragraphs:["Çerezler, bir internet sitesini ziyaret ettiğinizde tarayıcınız aracılığıyla cihazınıza kaydedilen küçük metin dosyalarıdır. Bu dosyalar, sitenin temel işlevlerini yerine getirmesine, tercihlerinizi hatırlamasına ve kullanım deneyiminin geliştirilmesine yardımcı olabilir.","Bu politika, Eşli Teknik web sitesinde çerezlerin ve benzer teknolojilerin hangi amaçlarla kullanılabileceğini açıklamak için hazırlanmıştır."]},
    {title:"Kullanılan Çerez Türleri",paragraphs:["Web sitemizde kullanım amacına ve saklama süresine göre farklı çerez türleri kullanılabilir:"],items:["Zorunlu çerezler: Sitenin güvenli ve doğru şekilde çalışması için gerekli olan çerezlerdir. Bu çerezler devre dışı bırakılamaz.","İşlevsel çerezler: Dil, görüntüleme veya tercih gibi seçimlerin hatırlanmasına yardımcı olan çerezlerdir.","Performans ve analiz çerezleri: Sitenin nasıl kullanıldığını anlamak, performansı ölçmek ve sayfaları geliştirmek amacıyla kullanılabilecek çerezlerdir.","Üçüncü taraf çerezleri: WhatsApp gibi üçüncü taraf hizmetlere yönlendiren bağlantılar veya gömülü hizmetler tarafından, kendi politikaları kapsamında yerleştirilebilecek çerezlerdir."]},
    {title:"Google Analytics",paragraphs:["Sitemizin hangi sayfalarının ziyaret edildiğini, ziyaretçilerin siteye hangi kanaldan (arama motoru, harita, sosyal medya vb.) ulaştığını ve WhatsApp ile telefon bağlantılarının ne sıklıkla kullanıldığını toplu olarak görmek için Google LLC tarafından sunulan Google Analytics hizmetini kullanıyoruz.","Google Analytics çerezleri yalnızca sitemizde görüntülenen çerez bildiriminde “Kabul et” seçeneğini işaretlemeniz hâlinde çalışır. “Reddet” seçeneğini işaretlerseniz bu çerezler yerleştirilmez ve ziyaretinize ilişkin analiz verisi gönderilmez. Reklam ve kişiselleştirme amaçlı çerez kullanılmaz.","Google Analytics kapsamında işlenen veriler Google’ın yurt dışındaki sunucularında işlenebilir. Google’ın veri işleme uygulamaları hakkında bilgi için policies.google.com/privacy adresindeki Google Gizlilik Politikası’nı inceleyebilirsiniz."]},
    {title:"Çerezlerin Kullanım Amaçları",paragraphs:["Çerezler, aşağıdaki amaçlarla kullanılabilir:"],items:["Web sitesinin temel işlevlerini ve güvenlik kontrollerini sağlamak","Sayfa tercihlerini ve oturumla ilgili teknik bilgileri hatırlamak","Ziyaretçi deneyimini ve site performansını değerlendirmek","İçerik ve hizmetleri daha anlaşılır, erişilebilir ve kullanışlı hale getirmek","Hataları tespit etmek ve teknik altyapının güvenilirliğini artırmak"]},
    {title:"Hangi Bilgiler İşlenebilir?",paragraphs:["Çerezler aracılığıyla tarayıcı türü, cihaz ve işletim sistemi bilgisi, ziyaret edilen sayfalar, ziyaret zamanı, yaklaşık kullanım ve etkileşim bilgileri gibi teknik veriler işlenebilir. Bu bilgiler, tek başına veya diğer verilerle birlikte kişiyi belirleyebilecek nitelikte olduğunda KVKK kapsamındaki yükümlülükler dikkate alınır.","Çerezler üzerinden elde edilen bilgiler, servis talebinin yürütülmesi için gerekli olmayan kişisel bilgilerin yerine geçmez. Servis talebi sırasında paylaştığınız ad, telefon ve adres bilgileri hakkında ayrıntılı bilgi için KVKK Aydınlatma Metni'ni inceleyebilirsiniz."]},
    {title:"Çerez Tercihlerinizi Yönetme",paragraphs:["Analiz çerezlerine ilişkin tercihinizi dilediğiniz zaman sayfanın alt bölümündeki “Çerez Tercihleri” bağlantısından değiştirebilirsiniz.","Tarayıcı ayarlarınız üzerinden çerezleri kabul edebilir, reddedebilir veya daha önce kaydedilmiş çerezleri silebilirsiniz. Zorunlu çerezleri engellemeniz halinde sitenin bazı işlevleri beklenildiği gibi çalışmayabilir.","Çerez yönetimi adımları tarayıcıya göre değişebilir. Kullandığınız tarayıcının yardım veya gizlilik ayarları bölümünden çerez tercihlerinizi güncelleyebilirsiniz."]},
    {title:"Üçüncü Taraf Hizmetler",paragraphs:["Web sitemizde yer alan WhatsApp iletişim bağlantısı gibi üçüncü taraf hizmetlere yönlendirmeler bulunabilir. Bu hizmetlerin kendi çerez ve gizlilik uygulamaları Eşli Teknik'ten bağımsızdır. İlgili hizmetleri kullanmadan önce üçüncü taraf sağlayıcının güncel politikalarını incelemeniz önerilir."]},
    {title:"Politika Değişiklikleri",paragraphs:["Eşli Teknik, web sitesindeki teknik veya hukuki gelişmelere bağlı olarak bu Çerez Politikası'nı güncelleyebilir. Güncel metin bu sayfada yayınlandığı tarihte geçerli olur."]},
    {title:"İletişim",paragraphs:["Çerez Politikası hakkında sorularınız veya talepleriniz için bizimle iletişime geçebilirsiniz."],contact:["Eşli Teknik / Mevlüt Esad EŞLİ","Telefon: 0 551 185 87 73","Web: www.esliteknik.com"]}
];
