/** Shared SEO content consumed by the React pages and static prerenderer. */

export const districtNeighborhoods:Record<string,string[]>={"Karatay":["Acıdort","Ağsaklı","Akabe","Akbaş","Akörenkışla","Araplar","Aziziye","Bakırtolu","Başak","Başgötüren","Beşağıl","Büyükburnak","Çatalhöyük","Çengilti","Çimenlik","Divanlar","Emirgazi","Erenler","Erler","Esentepe","Fetih","Fevziçakmak","Gaziosmanpaşa","Göçü","HacıVeyiszade","Hamzaoğlu","Hayıroğlu","İpekler","İsmil","İstiklal","İşgalaman","Kalenderhane","Karaaslan","Karadona","Karakaya","Katrancı","Keçeciler","Kızören","Köseali","Kumköprü","Mengene","Nakipoğlu","Obruk","Ortakonak","Ovakavağı","Sakyatan","Saraçoğlu","Sarıyakup","Sedirler","Selimsultan","Sultan Mesud","Sürüç","Şatır","Şemsi Tebrizi","Tatlıcak","Ulubatlıhasan","Yağlıbayat","Yarma","Yavşankuyu","Yediler","Yenice","Yenikent","Zincirli"],"Meram":["Alakova","Alavardı","Ali Ulvi Kurucu","Alpaslan","Aşkan","Ateşbaz Veli","Ayanbey","Aydoğdu","Aymanas","Bahçeşehir","Bayat","Boruktolu","Botsa","Boyalı","Çarıklar","Çaybaşı","Çayırbağı","Çomaklar","Çomaklı","Çukurçimen","Dere","Durunday","Erenkaya","Evliyatekke","Gödene","Hadimi","Harmancık","Hasanşeyh","Hatıp","Hatunsaray","Havzan","İkipınar","İnlice","Karaağaç","Karadiğin","Karadiğinderesi","Karahüyük","Kaşınhanı","Kavak","Kayadibi","Kayalı","Kayıhüyük","Kızılören","Kilistra","Konevi","Kovanağzı","Kozağaç","Köyceğiz","Kumralı","Lalebahçe","Melikşah","Osmangazi","Pamukçu","Pirebi","Sadıklar","Sağlık","Sahibata","Sarıkız","Sefaköy","Uluğbey","Uluırmak","Uzunharmanlar","Yaka","Yatağan","Yaylapınar","Yenibahçe","Yenişehir","Yeşildere","Yeşiltekke"],"Selçuklu":["Akademi","Akıncılar","Akpınar","Akşemsettin","Ardıçlı","Aşağıpınarbaşı","Aydınlık Evler","Bağrıkurt","Başarakavak","Bedir","Beyhekim","Biçer","Bilecik","Binkonutlar","Bosnahersek","Buhara","Büyükkayacık","Cumhuriyet","Çaldere","Çaltı","Çandır","Dağdere","Dokuz","Dumlupınar","Eğribayat","Erenköy","Esenler","Fatih","Ferhuniye","Feritpaşa","Güvenç","Hacıkaymak","Hanaybaşı","Hocacihan","Horozluhan","Hüsamettin Çelebi","Işıklar","İhsaniye","Kaleköy","Karaömerler","Kervan","Kılınçarslan","Kınık","Kızılcakuyu","Kosova","Küçükmuhsine","Malazgirt","Mehmet Akif","Meydanköy","Musalla Bağları","Nişantaş","Parsana","Sakarya","Sancak","Sarayköy","Sarıcalar","Selahaddini Eyyubi","Selahattin","Selçuk","Sızma","Sille","Sille Ak","Sulutas","Şeker","Şeyh Şamil","Tatköy","Tepekent","Tömek","Ulumuhsine","Yazıbelen","Yazır","Yukarıpınarbaşı"]};

export const relatedLinks:Record<string,{name:string;href:string}[]>={"Çamaşır Makinesi":[{name:"Kurutma Makinesi Tamiri",href:"/kurutma-makinesi-tamiri-konya/"},{name:"Bulaşık Makinesi Tamiri",href:"/bulasik-makinesi-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"}],"Bulaşık Makinesi":[{name:"Çamaşır Makinesi Tamiri",href:"/camasir-makinesi-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"},{name:"Fırın Tamiri",href:"/firin-tamiri-konya/"}],"Kurutma Makinesi":[{name:"Çamaşır Makinesi Tamiri",href:"/camasir-makinesi-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"},{name:"Elektrikli Süpürge Tamiri",href:"/elektrikli-supurge-tamiri-konya/"}],"Buzdolabı":[{name:"Derin Dondurucu Tamiri",href:"/derin-dondurucu-tamiri-konya/"},{name:"Su Sebili Tamiri",href:"/su-sebili-tamiri-konya/"},{name:"Bulaşık Makinesi Tamiri",href:"/bulasik-makinesi-tamiri-konya/"}],"Fırın":[{name:"Ocak Tamiri",href:"/ocak-tamiri-konya/"},{name:"Davlumbaz Tamiri",href:"/davlumbaz-tamiri-konya/"},{name:"Bulaşık Makinesi Tamiri",href:"/bulasik-makinesi-tamiri-konya/"}],"Ocak":[{name:"Fırın Tamiri",href:"/firin-tamiri-konya/"},{name:"Davlumbaz Tamiri",href:"/davlumbaz-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"}],"Karatay":[{name:"Çamaşır Makinesi Tamiri",href:"/camasir-makinesi-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"},{name:"Bulaşık Makinesi Tamiri",href:"/bulasik-makinesi-tamiri-konya/"}],"Meram":[{name:"Çamaşır Makinesi Tamiri",href:"/camasir-makinesi-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"},{name:"Fırın Tamiri",href:"/firin-tamiri-konya/"}],"Selçuklu":[{name:"Çamaşır Makinesi Tamiri",href:"/camasir-makinesi-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"},{name:"Bulaşık Makinesi Tamiri",href:"/bulasik-makinesi-tamiri-konya/"}]};


export const districtFaqs: Record<string, [string, string][]> = {
  Karatay: [["Karatay’da servis talebi oluşturmak için ne yazmalıyım?", "Cihaz türü, marka-model, arıza belirtisi, varsa hata kodu ve Karatay’daki açık adres bilgisi yeterlidir."], ["Karatay’da aynı gün servis yapılır mı?", "Aynı gün uygunluğu ekip planına ve adrese göre kontrol edilir. Uygun zaman servis talebi sırasında paylaşılır."]],
  Meram: [["Meram’da servis için mahalle bilgisi gerekli mi?", "Evet. Mahalle ve açık adres bilgisi, servis uygunluğunun kontrol edilmesi için gereklidir."], ["Meram’da servis süresi nasıl belirlenir?", "Cihazın arızası, gerekli işlem ve ekip uygunluğu değerlendirildikten sonra uygun zaman bilgisi paylaşılır."]],
  Selçuklu: [["Selçuklu’da servis kaydı nasıl açılır?", "WhatsApp’tan cihaz türünü, marka-model bilgisini, arıza belirtisini ve Selçuklu’daki açık adresinizi göndererek kayıt başlatabilirsiniz."], ["Selçuklu’da servis kaydını takip edebilir miyim?", "Evet. Kayıt açıldığında gönderilen özel takip bağlantısı üzerinden işlem durumunu görüntüleyebilirsiniz."]]
};


/** Detailed service FAQs used by both visible React content and prerendered SEO HTML. */
export const serviceFaqs: Record<string, [string, string][]> = {
  "Çamaşır Makinesi": [
    ["Çamaşır makinesi neden kötü kokar?", "Deterjan ve yumuşatıcı kalıntısı, kapak körüğünün içinde kalan su ve sürekli düşük sıcaklıkta yıkama koku yapan birikintiye yol açar. Kullanım sonrası kapağı ve deterjan çekmecesini aralık bırakın, körüğün iç kıvrımını silin ve kılavuzun önerdiği tambur temizleme programını düzenli çalıştırın. Koku yanık kokusuysa makineyi kullanmayın."],
    ["Çamaşır makinesi yumuşatıcıyı neden almaz?", "Yumuşatıcı bölmesindeki küçük sifon kapağının tıkanması veya yerinden çıkması, bölmenin MAX çizgisinin üzerinde doldurulması ya da düşük su basıncı yumuşatıcının bölmede kalmasına neden olur. Çekmeceyi çıkarıp sifon kapağını ılık suyla temizleyin ve yerine tam oturtun."],
    ["Program bitti ama kapak açılmıyor, ne yapmalıyım?", "Birçok makinede kapak kilidi program bittikten sonra birkaç dakika güvenlik için kapalı kalır. İçeride su varsa makine suyu boşaltmadan kapağı açmaz. Beklemeye rağmen açılmıyorsa kapağı zorlamayın; kilit mekanizması veya tahliye tarafı incelenmelidir."]
  ],
  "Bulaşık Makinesi": [
    ["Bulaşık makinesi neden kurutmaz?", "Parlatıcı haznesinin boş olması, düşük sıcaklıkta çalışan ekonomi programları ve plastik kapların ısıyı az tutması kurumayı zayıflatır; plastiklerin bir miktar ıslak kalması normaldir. Parlatıcıyı doldurup normal bir programda deneyin. Hiçbir programda kurutma olmuyorsa ısıtma ve kurutma sistemi incelenmelidir."],
    ["Bulaşık makinesi neden kötü kokar?", "Filtrede biriken yemek artıkları, kapak contası çevresindeki kir ve makinenin uzun süre kapalı bekletilmesi koku yapar. Filtreyi düzenli temizleyin, contayı silin, kullanmadığınız günlerde kapağı aralık bırakın ve ayda bir bulaşık makinesi temizleyicisiyle boş program çalıştırın."],
    ["Bulaşık makinesinde tuz ve parlatıcı neden gereklidir?", "Tuz, makinenin su yumuşatma sistemini yeniler ve bardaklarda kireç lekesi oluşmasını önler. Parlatıcı ise suyun yüzeyde damla bırakmadan akmasını sağlayarak kurutmaya yardım eder. Hepsi bir arada tabletler kullanılsa bile sert suda tuz haznesinin dolu tutulması önerilir."]
  ],
  "Buzdolabı": [
    ["Buzdolabı kaç derece olmalı?", "Gıda güvenliği için soğutucu bölmenin yaklaşık +4 °C, dondurucunun −18 °C civarında tutulması genel olarak önerilir. Ayar düğmesindeki rakamların hangi sıcaklığa karşılık geldiği modele göre değiştiği için kullanım kılavuzuna bakın; ayar değişikliğinden sonra iç sıcaklığın dengelenmesi birkaç saat sürer."],
    ["Buzdolabı gazının bittiği nasıl anlaşılır?", "Soğutma gazı kendiliğinden bitmez, ancak soğutma devresinde bir kaçak varsa azalır. Kompresör çalıştığı hâlde dolabın giderek daha az soğutması kaçak belirtisi olabilir. Kaçak noktası bulunup giderilmeden yapılan gaz dolumu kalıcı çözüm değildir."],
    ["Buzdolabı neden öter veya alarm verir?", "Kapının açık kalması ya da tam kapanmaması en yaygın nedendir. Uzun bir elektrik kesintisinden sonra iç sıcaklık yükseldiğinde de dijital ekranlı modeller uyarı verir. Kapı kapalıyken ve sıcaklık dengelendikten sonra uyarı sürüyorsa ekrandaki kodu not edip servis talebinizde paylaşın."]
  ],
  "Fırın": [
    ["Fırının ışığı yanmıyor ve ısıtmıyorsa ne yapmalıyım?", "Işık, ekran ve ısıtma birlikte çalışmıyorsa fırına enerji gelmiyor olabilir. Fırının bağlı olduğu sigortayı ve ana şalteri kontrol edin. Sigorta yerindeyse bağlantı, termik koruma veya kontrol kartı incelenmelidir; bu noktada fırının kablolarına müdahale etmeyin."],
    ["Fırın neden buğulanır veya su akıtır?", "Pişen yemekten çıkan buharın soğuk kapak camında yoğuşması normaldir ve özellikle ön ısıtma yapılmadan pişirilen sulu yemeklerde artar. Kapak kapalıyken dışarıya sürekli su veya buhar kaçıyorsa kapak contası gevşemiş ya da yırtılmış olabilir."],
    ["Ankastre fırın dolaptan çıkarılmadan tamir edilebilir mi?", "Arızaya göre değişir. Fan rezistansı gibi bazı parçalara fırının iç haznesinden ulaşılabilir; arka ve alt bölüme erişim gerektiren işlemlerde ise fırının dolaptan dikkatlice çıkarılması gerekir. Bu işlem servis sırasında teknisyen tarafından yapılır."]
  ],
  "Ocak": [
    ["Ocak ateşlemiyorsa ne kontrol edilir?", "Gaz vanası, elektrik bağlantısı ve düğme konumu gözlemlenebilir; ateşleme sistemini sökmeyin. Gaz kokusu varsa cihazı kullanmadan destek alın."],
    ["Ocakta sarı alev neden olur?", "Hava-gaz karışımı, enjektör veya yanma sistemiyle ilgili bir sorun olabilir. Ocağı kullanmayı bırakıp güvenli biçimde servis isteyin."],
    ["Ocak camı çatladıysa kullanılabilir mi?", "Hayır. Cam çatlağı güvenlik riski oluşturabilir; cihazı kullanmayın ve model bilgisiyle servis yönlendirmesi alın."],
    ["Takip linki nasıl çalışır?", "Servis kaydınız açıldıktan sonra size WhatsApp üzerinden özel bir bağlantı iletilir. Bağlantıdan işlem durumunu takip edebilirsiniz."],
    ["Aynı gün servis mümkün mü?", "Konya içindeki günlük planlama ve ekibin uygunluğuna göre aynı gün servis hedeflenir. Net bilgi talebinizde paylaşılır."]
  ],
  "Kurutma Makinesi": [
    ["Kurutma makinesi çamaşırları neden küçültür?", "Pamuklu ve yünlü gibi ısıya hassas kumaşlar yüksek sıcaklıkta ve uzun süre kurutulduğunda çeker. Çamaşır etiketindeki kurutma işaretine uyun, hassas giysiler için düşük ısılı programı seçin ve çamaşırları gereğinden fazla kurutmayın."],
    ["Kurutma seviyesi nasıl seçilmeli?", "Dolap kuruluğu çamaşırın doğrudan kaldırılabileceği seviyedir; ütü kuruluğu ise ütülemeyi kolaylaştırmak için hafif nem bırakır. Kalın ve ince kumaşları aynı yükte kurutmak eşit olmayan sonuç verir; benzer kalınlıktaki çamaşırları birlikte kurutun."],
    ["Kurutma makinesi çamaşır makinesinin üstüne konabilir mi?", "Birçok model üst üste yerleştirilebilir; ancak bunun için markaya uygun üst üste montaj aparatı kullanılmalıdır. Aparat olmadan yerleştirilen kurutma makinesi titreşimle kayabilir ve devrilme riski oluşturur."]
  ]
};
