/** Shared SEO content consumed by the React pages and static prerenderer. */

export const districtNeighborhoods:Record<string,string[]>={"Karatay":["Acıdort","Ağsaklı","Akabe","Akbaş","Akörenkışla","Araplar","Aziziye","Bakırtolu","Başak","Başgötüren","Beşağıl","Büyükburnak","Çatalhöyük","Çengilti","Çimenlik","Divanlar","Emirgazi","Erenler","Erler","Esentepe","Fetih","Fevziçakmak","Gaziosmanpaşa","Göçü","HacıVeyiszade","Hamzaoğlu","Hayıroğlu","İpekler","İsmil","İstiklal","İşgalaman","Kalenderhane","Karaaslan","Karadona","Karakaya","Katrancı","Keçeciler","Kızören","Köseali","Kumköprü","Mengene","Nakipoğlu","Obruk","Ortakonak","Ovakavağı","Sakyatan","Saraçoğlu","Sarıyakup","Sedirler","Selimsultan","Sultan Mesud","Sürüç","Şatır","Şemsi Tebrizi","Tatlıcak","Ulubatlıhasan","Yağlıbayat","Yarma","Yavşankuyu","Yediler","Yenice","Yenikent","Zincirli"],"Meram":["Alakova","Alavardı","Ali Ulvi Kurucu","Alpaslan","Aşkan","Ateşbaz Veli","Ayanbey","Aydoğdu","Aymanas","Bahçeşehir","Bayat","Boruktolu","Botsa","Boyalı","Çarıklar","Çaybaşı","Çayırbağı","Çomaklar","Çomaklı","Çukurçimen","Dere","Durunday","Erenkaya","Evliyatekke","Gödene","Hadimi","Harmancık","Hasanşeyh","Hatıp","Hatunsaray","Havzan","İkipınar","İnlice","Karaağaç","Karadiğin","Karadiğinderesi","Karahüyük","Kaşınhanı","Kavak","Kayadibi","Kayalı","Kayıhüyük","Kızılören","Kilistra","Konevi","Kovanağzı","Kozağaç","Köyceğiz","Kumralı","Lalebahçe","Melikşah","Osmangazi","Pamukçu","Pirebi","Sadıklar","Sağlık","Sahibata","Sarıkız","Sefaköy","Uluğbey","Uluırmak","Uzunharmanlar","Yaka","Yatağan","Yaylapınar","Yenibahçe","Yenişehir","Yeşildere","Yeşiltekke"],"Selçuklu":["Akademi","Akıncılar","Akpınar","Akşemsettin","Ardıçlı","Aşağıpınarbaşı","Aydınlık Evler","Bağrıkurt","Başarakavak","Bedir","Beyhekim","Biçer","Bilecik","Binkonutlar","Bosnahersek","Buhara","Büyükkayacık","Cumhuriyet","Çaldere","Çaltı","Çandır","Dağdere","Dokuz","Dumlupınar","Eğribayat","Erenköy","Esenler","Fatih","Ferhuniye","Feritpaşa","Güvenç","Hacıkaymak","Hanaybaşı","Hocacihan","Horozluhan","Hüsamettin Çelebi","Işıklar","İhsaniye","Kaleköy","Karaömerler","Kervan","Kılınçarslan","Kınık","Kızılcakuyu","Kosova","Küçükmuhsine","Malazgirt","Mehmet Akif","Meydanköy","Musalla Bağları","Nişantaş","Parsana","Sakarya","Sancak","Sarayköy","Sarıcalar","Selahaddini Eyyubi","Selahattin","Selçuk","Sızma","Sille","Sille Ak","Sulutas","Şeker","Şeyh Şamil","Tatköy","Tepekent","Tömek","Ulumuhsine","Yazıbelen","Yazır","Yukarıpınarbaşı"]};

export const relatedLinks:Record<string,{name:string;href:string}[]>={"Çamaşır Makinesi":[{name:"Kurutma Makinesi Tamiri",href:"/kurutma-makinesi-tamiri-konya/"},{name:"Bulaşık Makinesi Tamiri",href:"/bulasik-makinesi-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"}],"Bulaşık Makinesi":[{name:"Çamaşır Makinesi Tamiri",href:"/camasir-makinesi-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"},{name:"Fırın Tamiri",href:"/firin-tamiri-konya/"}],"Kurutma Makinesi":[{name:"Çamaşır Makinesi Tamiri",href:"/camasir-makinesi-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"},{name:"Elektrikli Süpürge Tamiri",href:"/elektrikli-supurge-tamiri-konya/"}],"Buzdolabı":[{name:"Derin Dondurucu Tamiri",href:"/derin-dondurucu-tamiri-konya/"},{name:"Su Sebili Tamiri",href:"/su-sebili-tamiri-konya/"},{name:"Bulaşık Makinesi Tamiri",href:"/bulasik-makinesi-tamiri-konya/"}],"Fırın":[{name:"Ocak Tamiri",href:"/ocak-tamiri-konya/"},{name:"Davlumbaz Tamiri",href:"/davlumbaz-tamiri-konya/"},{name:"Bulaşık Makinesi Tamiri",href:"/bulasik-makinesi-tamiri-konya/"}],"Ocak":[{name:"Fırın Tamiri",href:"/firin-tamiri-konya/"},{name:"Davlumbaz Tamiri",href:"/davlumbaz-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"}],"Karatay":[{name:"Çamaşır Makinesi Tamiri",href:"/camasir-makinesi-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"},{name:"Bulaşık Makinesi Tamiri",href:"/bulasik-makinesi-tamiri-konya/"}],"Meram":[{name:"Çamaşır Makinesi Tamiri",href:"/camasir-makinesi-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"},{name:"Fırın Tamiri",href:"/firin-tamiri-konya/"}],"Selçuklu":[{name:"Çamaşır Makinesi Tamiri",href:"/camasir-makinesi-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"},{name:"Bulaşık Makinesi Tamiri",href:"/bulasik-makinesi-tamiri-konya/"}]};


export const districtFaqs: Record<string, [string, string][]> = {
  Karatay: [["Karatay’da servis talebi oluşturmak için ne yazmalıyım?", "Cihaz türü, marka-model, arıza belirtisi, varsa hata kodu ve Karatay’daki açık adres bilgisi yeterlidir."], ["Karatay’da aynı gün servis yapılır mı?", "Aynı gün uygunluğu ekip planına ve adrese göre kontrol edilir. Uygun zaman servis talebi sırasında paylaşılır."]],
  Meram: [["Meram’da servis için mahalle bilgisi gerekli mi?", "Evet. Mahalle ve açık adres bilgisi, servis uygunluğunun kontrol edilmesi için gereklidir."], ["Meram’da servis süresi nasıl belirlenir?", "Cihazın arızası, gerekli işlem ve ekip uygunluğu değerlendirildikten sonra uygun zaman bilgisi paylaşılır."]],
  Selçuklu: [["Selçuklu’da servis kaydı nasıl açılır?", "WhatsApp’tan cihaz türünü, marka-model bilgisini, arıza belirtisini ve Selçuklu’daki açık adresinizi göndererek kayıt başlatabilirsiniz."], ["Selçuklu’da servis kaydını takip edebilir miyim?", "Evet. Kayıt açıldığında gönderilen özel takip bağlantısı üzerinden işlem durumunu görüntüleyebilirsiniz."]]
};
