/** Shared SEO content consumed by the React pages and static prerenderer. */

export const districtNeighborhoods:Record<string,string[]>={"Karatay":["Acıdort","Ağsaklı","Akabe","Akbaş","Akörenkışla","Araplar","Aziziye","Bakırtolu","Başak","Başgötüren","Beşağıl","Büyükburnak","Çatalhöyük","Çengilti","Çimenlik","Divanlar","Emirgazi","Erenler","Erler","Esentepe","Fetih","Fevziçakmak","Gaziosmanpaşa","Göçü","HacıVeyiszade","Hamzaoğlu","Hayıroğlu","İpekler","İsmil","İstiklal","İşgalaman","Kalenderhane","Karaaslan","Karadona","Karakaya","Katrancı","Keçeciler","Kızören","Köseali","Kumköprü","Mengene","Nakipoğlu","Obruk","Ortakonak","Ovakavağı","Sakyatan","Saraçoğlu","Sarıyakup","Sedirler","Selimsultan","Sultan Mesud","Sürüç","Şatır","Şemsi Tebrizi","Tatlıcak","Ulubatlıhasan","Yağlıbayat","Yarma","Yavşankuyu","Yediler","Yenice","Yenikent","Zincirli"],"Meram":["Alakova","Alavardı","Ali Ulvi Kurucu","Alpaslan","Aşkan","Ateşbaz Veli","Ayanbey","Aydoğdu","Aymanas","Bahçeşehir","Bayat","Boruktolu","Botsa","Boyalı","Çarıklar","Çaybaşı","Çayırbağı","Çomaklar","Çomaklı","Çukurçimen","Dere","Durunday","Erenkaya","Evliyatekke","Gödene","Hadimi","Harmancık","Hasanşeyh","Hatıp","Hatunsaray","Havzan","İkipınar","İnlice","Karaağaç","Karadiğin","Karadiğinderesi","Karahüyük","Kaşınhanı","Kavak","Kayadibi","Kayalı","Kayıhüyük","Kızılören","Kilistra","Konevi","Kovanağzı","Kozağaç","Köyceğiz","Kumralı","Lalebahçe","Melikşah","Osmangazi","Pamukçu","Pirebi","Sadıklar","Sağlık","Sahibata","Sarıkız","Sefaköy","Uluğbey","Uluırmak","Uzunharmanlar","Yaka","Yatağan","Yaylapınar","Yenibahçe","Yenişehir","Yeşildere","Yeşiltekke"],"Selçuklu":["Akademi","Akıncılar","Akpınar","Akşemsettin","Ardıçlı","Aşağıpınarbaşı","Aydınlık Evler","Bağrıkurt","Başarakavak","Bedir","Beyhekim","Biçer","Bilecik","Binkonutlar","Bosnahersek","Buhara","Büyükkayacık","Cumhuriyet","Çaldere","Çaltı","Çandır","Dağdere","Dokuz","Dumlupınar","Eğribayat","Erenköy","Esenler","Fatih","Ferhuniye","Feritpaşa","Güvenç","Hacıkaymak","Hanaybaşı","Hocacihan","Horozluhan","Hüsamettin Çelebi","Işıklar","İhsaniye","Kaleköy","Karaömerler","Kervan","Kılınçarslan","Kınık","Kızılcakuyu","Kosova","Küçükmuhsine","Malazgirt","Mehmet Akif","Meydanköy","Musalla Bağları","Nişantaş","Parsana","Sakarya","Sancak","Sarayköy","Sarıcalar","Selahaddini Eyyubi","Selahattin","Selçuk","Sızma","Sille","Sille Ak","Sulutas","Şeker","Şeyh Şamil","Tatköy","Tepekent","Tömek","Ulumuhsine","Yazıbelen","Yazır","Yukarıpınarbaşı"]};

export const relatedLinks:Record<string,{name:string;href:string}[]>={"Çamaşır Makinesi":[{name:"Kurutma Makinesi Tamiri",href:"/kurutma-makinesi-tamiri-konya/"},{name:"Bulaşık Makinesi Tamiri",href:"/bulasik-makinesi-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"}],"Bulaşık Makinesi":[{name:"Çamaşır Makinesi Tamiri",href:"/camasir-makinesi-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"},{name:"Fırın Tamiri",href:"/firin-tamiri-konya/"}],"Kurutma Makinesi":[{name:"Çamaşır Makinesi Tamiri",href:"/camasir-makinesi-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"},{name:"Elektrikli Süpürge Tamiri",href:"/elektrikli-supurge-tamiri-konya/"}],"Buzdolabı":[{name:"Derin Dondurucu Tamiri",href:"/derin-dondurucu-tamiri-konya/"},{name:"Su Sebili Tamiri",href:"/su-sebili-tamiri-konya/"},{name:"Bulaşık Makinesi Tamiri",href:"/bulasik-makinesi-tamiri-konya/"}],"Fırın":[{name:"Ocak Tamiri",href:"/ocak-tamiri-konya/"},{name:"Davlumbaz Tamiri",href:"/davlumbaz-tamiri-konya/"},{name:"Bulaşık Makinesi Tamiri",href:"/bulasik-makinesi-tamiri-konya/"}],"Ocak":[{name:"Fırın Tamiri",href:"/firin-tamiri-konya/"},{name:"Davlumbaz Tamiri",href:"/davlumbaz-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"}],"Karatay":[{name:"Çamaşır Makinesi Tamiri",href:"/camasir-makinesi-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"},{name:"Bulaşık Makinesi Tamiri",href:"/bulasik-makinesi-tamiri-konya/"}],"Meram":[{name:"Çamaşır Makinesi Tamiri",href:"/camasir-makinesi-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"},{name:"Fırın Tamiri",href:"/firin-tamiri-konya/"}],"Selçuklu":[{name:"Çamaşır Makinesi Tamiri",href:"/camasir-makinesi-tamiri-konya/"},{name:"Buzdolabı Tamiri",href:"/buzdolabi-tamiri-konya/"},{name:"Bulaşık Makinesi Tamiri",href:"/bulasik-makinesi-tamiri-konya/"}]};


export const districtFaqs: Record<string, [string, string][]> = {
  Karatay: [["Karatay’da servis talebi oluşturmak için ne yazmalıyım?", "Cihaz türü, marka-model, arıza belirtisi, varsa hata kodu ve Karatay’daki açık adres bilgisi yeterlidir."], ["Karatay’da aynı gün servis yapılır mı?", "Aynı gün uygunluğu ekip planına ve adrese göre kontrol edilir. Uygun zaman servis talebi sırasında paylaşılır."]],
  Meram: [["Meram’da servis için mahalle bilgisi gerekli mi?", "Evet. Mahalle ve açık adres bilgisi, servis uygunluğunun kontrol edilmesi için gereklidir."], ["Meram’da servis süresi nasıl belirlenir?", "Cihazın arızası, gerekli işlem ve ekip uygunluğu değerlendirildikten sonra uygun zaman bilgisi paylaşılır."]],
  Selçuklu: [["Selçuklu’da servis kaydı nasıl açılır?", "WhatsApp’tan cihaz türünü, marka-model bilgisini, arıza belirtisini ve Selçuklu’daki açık adresinizi göndererek kayıt başlatabilirsiniz."], ["Selçuklu’da servis kaydını takip edebilir miyim?", "Evet. Kayıt açıldığında gönderilen özel takip bağlantısı üzerinden işlem durumunu görüntüleyebilirsiniz."]]
};


/** Detailed service FAQs used by both visible React content and prerendered SEO HTML. */
export const serviceFaqs: Record<string, [string, string][]> = {
  "Çamaşır Makinesi": [
    ["Çamaşır makinesi neden kötü kokar?", "Deterjan ve yumuşatıcı kalıntısı, kapak körüğünün içinde kalan su ve sürekli düşük sıcaklıkta yıkama koku yapan birikintiye yol açar. Kullanım sonrası kapağı ve deterjan çekmecesini aralık bırakın, körüğün iç kıvrımını silin ve kılavuzun önerdiği tambur temizleme programını düzenli çalıştırın. Koku yanık kokusuysa makineyi kullanmayın."],
    ["Çamaşır makinesi yumuşatıcıyı neden almaz?", "Yumuşatıcı bölmesindeki küçük sifon kapağının tıkanması veya yerinden çıkması, bölmenin MAX çizgisinin üzerinde doldurulması ya da düşük su basıncı yumuşatıcının bölmede kalmasına neden olur. Çekmeceyi çıkarıp sifon kapağını ılık suyla temizleyin ve yerine tam oturtun."],
    ["Program bitti ama kapak açılmıyor, ne yapmalıyım?", "Birçok makinede kapak kilidi program bittikten sonra birkaç dakika güvenlik için kapalı kalır. İçeride su varsa makine suyu boşaltmadan kapağı açmaz. Beklemeye rağmen açılmıyorsa kapağı zorlamayın; kilit mekanizması veya tahliye tarafı incelenmelidir."]
  ],
  "Bulaşık Makinesi": [
    ["Bulaşık makinesi neden kurutmaz?", "Parlatıcı haznesinin boş olması, düşük sıcaklıkta çalışan ekonomi programları ve plastik kapların ısıyı az tutması kurumayı zayıflatır; plastiklerin bir miktar ıslak kalması normaldir. Parlatıcıyı doldurup normal bir programda deneyin. Hiçbir programda kurutma olmuyorsa ısıtma ve kurutma sistemi incelenmelidir."],
    ["Bulaşık makinesi neden kötü kokar?", "Filtrede biriken yemek artıkları, kapak contası çevresindeki kir ve makinenin uzun süre kapalı bekletilmesi koku yapar. Filtreyi düzenli temizleyin, contayı silin, kullanmadığınız günlerde kapağı aralık bırakın ve ayda bir bulaşık makinesi temizleyicisiyle boş program çalıştırın."],
    ["Bulaşık makinesinde tuz ve parlatıcı neden gereklidir?", "Tuz, makinenin su yumuşatma sistemini yeniler ve bardaklarda kireç lekesi oluşmasını önler. Parlatıcı ise suyun yüzeyde damla bırakmadan akmasını sağlayarak kurutmaya yardım eder. Hepsi bir arada tabletler kullanılsa bile sert suda tuz haznesinin dolu tutulması önerilir."]
  ],
  "Buzdolabı": [
    ["Buzdolabı kaç derece olmalı?", "Gıda güvenliği için soğutucu bölmenin yaklaşık +4 °C, dondurucunun −18 °C civarında tutulması genel olarak önerilir. Ayar düğmesindeki rakamların hangi sıcaklığa karşılık geldiği modele göre değiştiği için kullanım kılavuzuna bakın; ayar değişikliğinden sonra iç sıcaklığın dengelenmesi birkaç saat sürer."],
    ["Buzdolabı gazının bittiği nasıl anlaşılır?", "Soğutma gazı kendiliğinden bitmez, ancak soğutma devresinde bir kaçak varsa azalır. Kompresör çalıştığı hâlde dolabın giderek daha az soğutması kaçak belirtisi olabilir. Kaçak noktası bulunup giderilmeden yapılan gaz dolumu kalıcı çözüm değildir."],
    ["Buzdolabı neden öter veya alarm verir?", "Kapının açık kalması ya da tam kapanmaması en yaygın nedendir. Uzun bir elektrik kesintisinden sonra iç sıcaklık yükseldiğinde de dijital ekranlı modeller uyarı verir. Kapı kapalıyken ve sıcaklık dengelendikten sonra uyarı sürüyorsa ekrandaki kodu not edip servis talebinizde paylaşın."]
  ],
  "Fırın": [
    ["Fırının ışığı yanmıyor ve ısıtmıyorsa ne yapmalıyım?", "Işık, ekran ve ısıtma birlikte çalışmıyorsa fırına enerji gelmiyor olabilir. Fırının bağlı olduğu sigortayı ve ana şalteri kontrol edin. Sigorta yerindeyse bağlantı, termik koruma veya kontrol kartı incelenmelidir; bu noktada fırının kablolarına müdahale etmeyin."],
    ["Fırın neden buğulanır veya su akıtır?", "Pişen yemekten çıkan buharın soğuk kapak camında yoğuşması normaldir ve özellikle ön ısıtma yapılmadan pişirilen sulu yemeklerde artar. Kapak kapalıyken dışarıya sürekli su veya buhar kaçıyorsa kapak contası gevşemiş ya da yırtılmış olabilir."],
    ["Ankastre fırın dolaptan çıkarılmadan tamir edilebilir mi?", "Arızaya göre değişir. Fan rezistansı gibi bazı parçalara fırının iç haznesinden ulaşılabilir; arka ve alt bölüme erişim gerektiren işlemlerde ise fırının dolaptan dikkatlice çıkarılması gerekir. Bu işlem servis sırasında teknisyen tarafından yapılır."]
  ],
  "Ocak": [
    ["LPG tüpten doğalgaza (veya tam tersi) geçerken ocakta değişiklik gerekir mi?", "Evet. Ocaklar LPG ve doğalgaz için farklı enjektörlerle üretilir; gaz türü değiştiğinde enjektörlerin ve bazı modellerde regülatörün uygun olanla değiştirilmesi gerekir. Uygun olmayan enjektörle çalıştırılan ocak sarı alev, is ve yetersiz ısıtma yapabilir. Bu değişim gaz tesisatına hakim bir teknisyen tarafından yapılmalıdır."],
    ["Ocağın düğmelerini veya camını nasıl temizlemeliyim?", "Çıkarılabilen düğmeleri ılık sabunlu suda bekletip iyice kuruttuktan sonra takın; ıslak düğmeyi takmak elektronik ateşlemeli modellerde arızaya yol açabilir. Cam yüzeyli ocaklarda çizilmeyi önlemek için aşındırıcı sünger yerine yumuşak bez ve cam ocaklara uygun temizlik ürünü kullanın. Taşan yemeği soğumadan kazımaya çalışmayın."],
    ["Ankastre ocağı kendim tezgahtan söküp taşıyabilir miyim?", "Ankastre ocaklar gaz ve/veya elektrik bağlantısına sahip olduğundan taşınma, tadilat ya da temizlik amacıyla kendi başınıza sökülmesi önerilmez. Gaz bağlantısının usulüne uygun kapatılıp yeniden kurulmaması kaçak riski oluşturabilir; bu işlemin teknisyen tarafından yapılması güvenlidir."]
  ],
  "Elektrikli Süpürge": [
    ["Torbasız (siklonik) süpürgelerde filtre bakımı nasıl yapılmalı?", "Siklonik modellerde hazne ve filtreler düzenli olarak boşaltılıp yıkanmalı; yıkanabilir filtreler tekrar takılmadan önce tamamen kurutulmalıdır, çünkü ıslak filtre motora nem taşıyabilir. Filtre değişim aralığı kullanım kılavuzunda belirtilir ve düzenli bakım emişin uzun süre güçlü kalmasını sağlar."],
    ["Süpürge hangi zeminlerde hangi başlıkla kullanılmalı?", "Halı için döner fırçalı başlık, parke ve laminat gibi sert zeminler için yumuşak fırçalı veya fırçasız başlık tercih edilmesi hem temizlik kalitesini artırır hem de yüzeyde çizik oluşmasını önler. Yanlış başlık kullanımı hem zemine zarar verebilir hem de emişi azaltabilir."],
    ["Robot süpürge haritayı neden sürekli sıfırdan çıkarıyor?", "Ortamdaki mobilya düzeninin sık değişmesi, sensörlerin toz veya kir ile kaplanması ya da zayıf sinyal alanı haritanın kaydedilmesini veya hatırlanmasını zorlaştırabilir. Sensörlerin ve tekerleklerin düzenli temizlenmesi, cihazın şarj istasyonuna net bir görüş hattıyla yerleştirilmesi haritalamayı iyileştirir."]
  ],
  "Davlumbaz": [
    ["Karbon filtre ne zaman değiştirilmeli, yağ filtresinden farkı nedir?", "Yağ filtresi havadaki yağ zerreciklerini tutar ve yıkanarak tekrar kullanılabilir; karbon filtre ise resirkülasyonlu (bacasız) kullanımda kokuyu tutar, yıkanamaz ve belirli aralıklarla değiştirilmesi gerekir. Karbon filtre doygunlaştığında koku giderme etkisi azalır ve mutfakta yemek kokusu daha uzun süre kalır."],
    ["Davlumbaz bacası (boru) ne kadar uzun ve kaç dirsekli olabilir?", "Baca borusunun gereğinden uzun olması veya çok sayıda dar açılı dirsek içermesi hava direncini artırarak emiş gücünü düşürür; üretici kılavuzları genellikle mümkün olan en kısa ve en az dirsekli bağlantıyı önerir. Kurulum sırasında baca güzergâhının doğru planlanması bu yüzden önemlidir."],
    ["Davlumbazın motor gücü mutfağın büyüklüğüne uygun mu, nasıl anlaşılır?", "Davlumbazın hava debisi, mutfağın hacmine ve tavan yüksekliğine göre yeterli olmalıdır; düşük debili bir davlumbaz büyük veya açık mutfaklarda dumanı ve kokuyu yeterince çekemeyebilir. Bu bilgi genellikle cihazın etiketinde veya kullanım kılavuzunda yer alır."]
  ],
  "Derin Dondurucu": [
    ["Derin dondurucu kaç derecede tutulmalı?", "Gıda güvenliği için derin dondurucunun genellikle −18 °C civarında tutulması önerilir; bu sıcaklık gıdaların uzun süre güvenle saklanmasını sağlar. Kapağın sık açılması veya çok fazla ürünün aynı anda konulması iç sıcaklığın geçici olarak yükselmesine neden olabilir."],
    ["Sandık tipi ve çekmeceli/dikey derin dondurucu arasındaki fark nedir?", "Sandık tipi modeller üstten açılır, soğuk havayı içeride daha iyi tuttuğu için enerji açısından avantajlıdır ancak dipteki ürünlere erişim daha zordur. Çekmeceli/dikey modellerde ürünlere erişim kolaydır ve düzenleme yapmak daha pratiktir, ancak kapı her açıldığında soğuk hava dışarı kaçabilir."],
    ["Elektrik kesintisinde derin dondurucudaki ürünler ne kadar dayanır?", "Kapağı kapalı tutulan dolu bir derin dondurucu, kısa süreli elektrik kesintilerinde genellikle birkaç saat boyunca güvenli sıcaklığı koruyabilir; boş veya yarı dolu dondurucularda bu süre daha kısadır. Uzun kesintilerde kapağı gereksiz açmamak ürünlerin daha uzun süre donuk kalmasını sağlar."]
  ],
  "Su Sebili": [
    ["Sıcak su veren su sebillerinde çocuk kilidi nasıl çalışır?", "Çoğu modelde sıcak su musluğu, kazara dokunmayı önlemek için ayrı bir kilit düğmesi veya iki adımlı basma mekanizmasıyla korunur; sıcak su almak için önce kilidi açıp ardından musluğu çalıştırmak gerekir. Bu mekanizmanın sertleşmesi veya tam kilitlenmemesi kullanım kılavuzunda belirtilen şekilde kontrol edilebilir."],
    ["Damacana sebile takıldıktan sonra neden kabarcık çıkarıyor?", "Damacana takıldığında hazneye su akarken içerideki havanın dışarı çıkması nedeniyle bir miktar kabarcıklanma ve gulplama sesi normaldir; bu birkaç dakika içinde durur. Ses uzun süre kesilmiyorsa damacananın ağzının tam açılmadığı ya da yanlış oturduğu düşünülebilir."],
    ["Alttan damacanalı su sebili ile üstten damacanalı arasındaki fark nedir?", "Üstten damacanalı modellerde damacana sebilin üzerine ters çevrilerek yerleştirilir; alttan damacanalı modellerde ise damacana tabanda durur ve su bir pompa yardımıyla yukarı çekilir. Alttan damacanalı sistemler damacanayı kaldırma zorluğunu ortadan kaldırır ancak pompa bakımı gerektirir."]
  ],
  "Kurutma Makinesi": [
    ["Kurutma makinesi çamaşırları neden küçültür?", "Pamuklu ve yünlü gibi ısıya hassas kumaşlar yüksek sıcaklıkta ve uzun süre kurutulduğunda çeker. Çamaşır etiketindeki kurutma işaretine uyun, hassas giysiler için düşük ısılı programı seçin ve çamaşırları gereğinden fazla kurutmayın."],
    ["Kurutma seviyesi nasıl seçilmeli?", "Dolap kuruluğu çamaşırın doğrudan kaldırılabileceği seviyedir; ütü kuruluğu ise ütülemeyi kolaylaştırmak için hafif nem bırakır. Kalın ve ince kumaşları aynı yükte kurutmak eşit olmayan sonuç verir; benzer kalınlıktaki çamaşırları birlikte kurutun."],
    ["Kurutma makinesi çamaşır makinesinin üstüne konabilir mi?", "Birçok model üst üste yerleştirilebilir; ancak bunun için markaya uygun üst üste montaj aparatı kullanılmalıdır. Aparat olmadan yerleştirilen kurutma makinesi titreşimle kayabilir ve devrilme riski oluşturur."]
  ]
};
